### ISSUE TITLE
Reflecting matched media

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/picture-element#1]
We need to define the use cases (if any) for returning media that matched the selection of an image. 
That is: 

``` javascript
var resimg = $("#myresimg"); 
//which media matches 
if(resimg.media .... ){
  // 
}

```

We have the option to either return a string or a MediaList. We need to investigate which one we want to use. 

``` javascript
var resimg = $("#myresimg"); 
//which media matches 
if(resimg.mediaText === "screen"){
  // 
}

```

Media lists are cool because they have the following: 

``` javascript
[Constructor(DOMString text)]
interface MediaList {
    stringifier attribute DOMString mediaText;
    readonly attribute unsigned long length;
    DOMString item (unsigned long index);
    void appendMedium (DOMString medium);
    void deleteMedium (DOMString medium);
};
```

**Comment by yoavweiss** [comment]
Anyone has a use-case for a dev to know which `media` matched the `source` that was loaded inside `picture` (not to be confused with the matching `source`'s `src` attribute)?

**Comment by anselmh** [comment]
Isn't that needed for every JS MQ based image manipulation? Use case could be an image editor for example…

**Comment by yoavweiss** [comment]
Can you please describe why would a dev need the matched media in this case (rather than simply the loaded resource's URL). I'm not sure I get why it is necessary.

Bare in mind that given the loaded resource and the internal DOM of picture, finding the matched media in JS is simple (even if cumbersome). So if the use-case is marginal, it may not worth spending much time on it at this point facilitating it (which doesn't mean an easier way can't be added later on)

**Comment by anselmh** [comment]
You're totally right here, @yoavweiss, it may not be worth it. So forget about my use case and let's see if someone else has some.

**Comment by marcoscaceres** [comment]
I agree with @yoavweiss also. We should do bare minimum to address our documented use cases and then extend if we need to.

**Comment by nwtn** [comment]
Nobody has come forward with other use cases. Are we ok to close this and go with @yoavweiss and @marcoscaceres's conclusions?

**Comment by yoavweiss** [comment]
I'm cool with closing this issue. @marcoscaceres, if you agree, close away.
