### ISSUE TITLE
Indentation in example code not aligned properly

### ISSUE THREAD

**Issue by iandevlin** [ResponsiveImagesCG/picture-element#10]
A minor issue for sure, but it aids readability of the specification.

In many of the examples provided in the spec. (e.g. Example 1 and 2) the first source element within a picture element is indented correctly, but subsequent ones are indented further which at first glance makes them look to be child elements of the first source element.

**Comment by marcoscaceres** [comment]
@iandevlin I agree. If you want to do a pull request and fix up the markup, that would be awesome. Otherwise, I can try to fix it in the next few days.

**Comment by iandevlin** [comment]
Done, hopefully correctly, as it was my first ever pull request.

**Comment by marcoscaceres** [comment]
perfectly done! :)

**Comment by marcoscaceres** [comment]
@iandevlin, sorry, I forgot to mention that the index.html files are automagically generated. So in the future, you only need to update the *.src.html files.

**Comment by iandevlin** [comment]
Yes I realised that after I had already edited  the index.html file. Ah well.
