### ISSUE TITLE
Error handling for sizes attribute

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#113]
#97 is about srcset, let's talk about sizes.

Pondering about it a bit, I think it makes more sense to use CSS rules for sizes than it does for srcset. sizes can contain media queries, and media="" already uses CSS rules in HTML. Also it's supposed to support things like `calc` or other things CSS supports in place of a `<length>`.

Right now, if sizes fails to parse, the attribute is ignored. Is that what we want?

Take this example from the spec:

```
<picture>
  <source sizes="(max-width: 30em) 100%, (max-width: 50em) 50%, calc(33% - 100px)"
          srcset="pic100.jpg 100w, pic200.jpg 200w, pic400.jpg 400w,
                  pic800.jpg 800w, pic1600.jpg 1600w, pic3200.jpg 3200w">
  <img src="pic400.jpg" alt="The president giving an award.">
</picture>
```

If the UA doesn't support `calc`, then it acts as if sizes was absent. Do we instead want to act as if `sizes="(max-width: 30em) 100%, (max-width: 50em) 50%"` (so that the browser at least does the right thing for 2 of the 3 layouts)? Or skip the whole `source` (so the author can specify a fallback `source` without using calc)? Something else?

**Comment by yoavweiss** [comment]
I think that skipping the whole source, so that a fallback sizes can be defined is better for future compat. In the "just use <hat you understand" option, authors cannot define a fallback for older browsers.

OTOH, if the author haven't defined a fallback source, older browsers will get a significantly worse experience with this option.

I guess it boils down to what is more probable. Do we think that authors are likely to define fallback content?

**Comment by zcorpan** [comment]
Realistically speaking, it seems unlikely that authors will include a fallback `source`. It seems more probable that they will avoid using `calc` until it is supported or use a polyfill. From that perspective it seems unnecessary to tweak the behavior.

**Comment by zcorpan** [comment]
@tabatkins in #86 says that invalid `sizes` will result in the `source` being skipped (although that's not what the current spec says).

**Comment by tabatkins** [comment]
Hm, that's a problem.  It should skip things.  I'll fix.
