### ISSUE TITLE
Authoring conformance when sizes is present

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#114]
It doesn't make sense to do `<img sizes="100%" srcset="foo.jpg, bar.jpg 2x, baz.jpg 600w">` however that is allowed. I think when the sizes attribute is present, all image sources in the source set must have the width descriptor specified.

**Comment by zcorpan** [comment]
And maybe also vice versa. When sizes is not specified, the width descriptor must not be specified.

**Comment by yoavweiss** [comment]
That makes sense. Do you think we should drop the entire source in this case? or possibly the entire image loading process? (that'd get the author's attention :) )

**Comment by zcorpan** [comment]
I'm not suggesting to change the processing for UAs.
