### ISSUE TITLE
Authoring conformance for the media attribute

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#115]
It only makes sense to use multiple source elements (counting the img if it has a srcset attribute) if all or all but the last one uses the media attribute.

For example, the following is pointless since the second source will never be considered:

```
<picture>
 <source srcset="foo.jpg">
 <source srcset="bar.jpg 2x">
 <img ...>
</picture>
```

**Comment by yoavweiss** [comment]
that's true, but do you want to  explicitly forbid that? if so, what should we do in this case?

I think we should leave that as an permitted (possibly frowned upon by Dev tools) authoring mistake.

**Comment by zcorpan** [comment]
Authoring conformance criteria is about whether a validator should whine or not. If it is an authoring mistake and you would like Dev tools to point it out, I think it makes sense to forbid it in the spec. The processing for UAs is not affected.

**Comment by yoavweiss** [comment]
Didn't know that. Sounds like a good idea then.
