### ISSUE TITLE
Include section to explain the difference from <object>

### ISSUE THREAD

**Issue by myakura** [ResponsiveImagesCG/picture-element#12]
The content model and semantics looks like `<object>` in HTML4, so people might wonder why introducing a new element than extending `<object>`. There's a section explaining the difference between `<img>` and `<picture>` in the current draft. Why not have another one to explain the difference from `<object>`?

**Comment by marcoscaceres** [comment]
@myakura I'm happy to include it if you write up a first draft (I don't know enough about object's processing model to make the comparison). Just do a pull request or paste some draft text here.

**Comment by yoavweiss** [comment]
@myakura - Are you interested in adding the comparison? If not, can you please close this issue?

**Comment by myakura** [comment]
@yoavweiss would like to do so, but I don't have time now for this. Sorry, closing this.
