### ISSUE TITLE
Syntax for srcset when descriptors are omitted

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#123]
srcset allows a list of http://picture.responsiveimages.org/#image-candidate-string separated by comma, but that allows the following:

```
srcset="url1,url2"
```

We need to somehow require a space before or after the comma when no descriptor is present.

(This bug is not about the parsing.)

**Comment by yoavweiss** [comment]
Just to make sure I understand correctly, currently it would be parsed as a single URL"url1,url2", right?

**Comment by zcorpan** [comment]
Yep.

**Comment by yoavweiss** [comment]
So how would a validator distinguish between a URL with a comma in it to a situation like your example?
`srcset="url,with,a,comma"` is a perfectly valid value, right?

**Comment by zcorpan** [comment]
It wouldn't be able to distinguish.

**Comment by yoavweiss** [comment]
In that case, I don't think I understand the bug.

What do you think we need to add to the spec regarding that fact? A note aimed at authors, warning them of that possible authoring error?

**Comment by zcorpan** [comment]
The spec currently says that correct syntax for representing two comma-separated 'image candidate strings', which is wrong since it will parse as one item, not two as intended. So we need to correct the spec's normative syntax requirements for authors to require a space.
