### ISSUE TITLE
Spec text query: why specify height & width on some imgs but not all

### ISSUE THREAD

**Issue by brucelawson** [ResponsiveImagesCG/picture-element#125]
Some of the examples have width="500" height="500", eg examples 2 and 3. So naturally, I looked to see the significance of their being on some, but not all. I couldn't understand why. So please clarify why they're on some, or else put them on all, or remove them from all.

**Comment by yoavweiss** [comment]
According to the discussion on https://github.com/ResponsiveImagesCG/picture-element/issues/82 I think we should simply remove height/width in these examples. Maybe we should add them for the DPR switching only case (example 1)

**Comment by yoavweiss** [comment]
Closed by #126

**Comment by brucelawson** [comment]
yay, thanks
