### ISSUE TITLE
Why is the type attribute of source ignored?

### ISSUE THREAD

**Issue by mtolk** [ResponsiveImagesCG/picture-element#13]
In the spec under, Algorithm for deriving the source image, it says:
    "To avoid complexity, the type attribute is all child source elements is ignored in this context."

If you want to download the smallest possible image that a browser can handle the type attribute can be very usefull.

Please see  this [example](https://raw.github.com/nwtn/picturefill/master/index.pictureelement.html) by David Newton in a picturefill fork.

Browser that support it can use the smaller webp. Other browsers can fall back to jpg. 
This would also make the picture/source future-proof as it would allow for support of new imagetypes.

Maybe I'm missing something but is this really that complex?

**Comment by anselmh** [comment]
IMO this is a valid point. I would say the developer should be able to set type attr if he decides he wants to use this kind of differentiation.

---

Anselm

**Comment by marcoscaceres** [comment]
@mtolk this was my fault. The described algorithm is currently just a strawman proposal and I was trying to avoid some complexity. I have now added some text that first checks the if the `type` is supported by the browser. The proposed algorithm is by no means robust, it's just a point for discussion. The document now says:

> So, to derive the source image: ignoring any sources whose type is not supported by the browser, gather all the media queries from the source elements' media attributes into a "stylesheet", in document order. 

@mtolk, if you are satisfied with the above change, please close the bug.

**Comment by mtolk** [comment]
@marcoscaceres. Sounds great.
