### ISSUE TITLE
Sizes parsing clarification

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#132]
According to [the sizes parsing algo](http://picture.responsiveimages.org/#parse-sizes-attr) the first part of `<source-size>` is a `<media-query>`. AFAIU this means that it can contain `not|only` and include media types.

Do I understand correctly?
And if so, it that the intention?

**Comment by yoavweiss** [comment]
If that wasn't the intention, should we define it as a [`<media-condition>`](http://dev.w3.org/csswg/mediaqueries-4/#typedef-media-condition) or as a [`<media-in-parens>`](http://dev.w3.org/csswg/mediaqueries-4/#typedef-media-in-parens)?

I tend to think that media-in-parens is enough, since all our examples are based on it, and I'm having a hard time thinking of use-cases that need more than that, and shouldn't get bumped to the art-direction case anyway.

**Comment by yoavweiss** [comment]
After a chat on IRC, I'm now convinced that this is fine. Closing

**Comment by tabatkins** [comment]
Actually, that's a mistake on my part.  I'd intended the sizes='' attribute to only use a media-condition.
