### ISSUE TITLE
Consider renaming source to something else

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#133]
>  Hixie: please don't overload `<source>` 
>  Hixie: i don't want to have to deal with a bug where `<source>` is in a shadow dom and then grafted into a `<video>` while the `<picture>` processing model is running and then on the next microtask it's moved to a different shadow dom with an `<audio>`

http://krijnhoetmer.nl/irc-logs/whatwg/20140402#l-816

I'm not so familiar with shadow DOM myself to follow why it's problematic, but Hixie may be right in that it will be trouble to use the same tag name as `video`'s `source`.

**Comment by yoavweiss** [comment]
I have no strong feelings either way.

**Comment by Wilto** [comment]
I think that’s getting into weird territory for authors when combined with the `src` -> `srcset` change, but I’m withholding my say until we’ve nailed down exactly how likely we are to see issues like the one described above.

**Comment by marcoscaceres** [comment]
We probably need to reach out to @dglazkov for a definitive answer. I think I raised similar concerns about overloading `source` in the past but got told it was the "right thing to do"(tm) from at least one person knowledgeable of HTML parsing (why I kept that in the original design).

**Comment by tabatkins** [comment]
This is no more troublesome than the existing overloading of `<video>` and `<audio>` both using `<source>`.  The timing issue he brings up also already exists independently of any naming overlap; we need to make sure things are defined sanely for shadow DOM coming along and stealing children.

I think that right now, a `<source>` in shadow dom won't work with the host element.  Should we fix this?

You can, however, use a `<content>` element to _project_ a `<source>` that is a child of the host element into being a child of another `<source>`-using element in the shadow, like:

```
<picture>
  <source srcset="foo">
  <"shadow tree">
    <video>
      <content></content>
    </video>
  </"shadow tree">
</picture>
```

I think this will successfully grab the `<source>` from the `<picture>` and attach it to the `<video>` for processing.

**Comment by tabatkins** [comment]
> I think that right now, a `<source>` in shadow dom won't work with the host element. Should we fix this?

Nah, you can handle this yourself by just putting a your own `<picture>` into the shadow.  Once we have an attribute forwarding solution (planned for next level of shadow DOM), you can forward all the attributes from the host element to it, too.  (For now, you can just use a mutation observer on the host to move the attributes over and mirror any changes. More complex than I'd like, but not hard.)

**Comment by Wilto** [comment]
I feel better about keeping `source` as-is then, considering.

**Comment by zcorpan** [comment]
It seems to me there are some downsides with changing, too:
- A new element won't be void in existing UAs which would mess up the DOM and make it slightly harder to write polyfill. (We could repurpose an old void element that does nothing, like `basefont` or `bgsound` but that seems unlikely to be accepted by people who care about markup aesthetics.)
- We break familiarity with `video` markup. (This could be argued to be a benefit since they're different.)
- A new name might be longer and/or more awkward.

Also, to put things into perspective, there is precedent for using the same element for more than one purpose in HTML already:
- `option` is used by `select` and later repurposed for `datalist` (in part to enable better fallback for legacy UAs, but still).
- A single `link` element can have multiple purposes at the same time - it can have rel="icon stylesheet next" to create two external resource links and one hyperlink. Despite already being overloaded `link` was later extended to also participate in microdata.

As far as I know we haven't come to regret the above two decisions, it has been fine so far.

I'm sympathetic to Hixie's worry about having to deal with complications later on, but taking everything into consideration I'm leaning towards keeping `source` unless someone can more concretely describe a real problem with using `source` before it gets shipped.

**Comment by Hixie** [comment]
I'm not speccing this. So either it changes name, or you also take over the whole media section.

**Comment by Wilto** [comment]
Just to be clear on this, @Hixie: you’re refusing to spec something being actively implemented by multiple major browsers, on the basis that you personally disagree with it?

**Comment by Hixie** [comment]
No, I'm refusing to spec something that is a bad design, which I've learnt was a bad design because I made the same mistake years ago. If people want to repeat this mistake that's fine, but they have to take the responsibility to pay the cost. I'm willing to pay the cost of &lt;audio>/&lt;video>/Vsource>, because that was my mistake. This, however, is not my mistake, and I'm not willing to pay that cost.

zcorpan has already agreed to pay the cost of speccing &lt;picture> et al. All I'm saying here is that if he wants to compound this mistake by also making it collide with &lt;source>, then he should also pay the cost of that collision also.

**Comment by scottjehl** [comment]
I agree with @zcorpan and @tabatkins, though I'm admittedly unaware of the the specification costs that @Hixie is referring to. 

I think the benefits in familiarity to authors are pretty clear for `source`, as the element is already used by authors when listing potential sources for other types of media (`audio` and `video`). 

If it's not a blocking conflict for implementation and the benefits are known, isn't this just a matter of  [priority of constituencies](http://www.w3.org/TR/html-design-principles/#priority-of-constituencies)?

**Comment by kornelski** [comment]
@Hixie The current `<picture>` spec is not using the old messy media selection algorithm that early drafts had. In the latest spec processing of sources _cannot be interrupted_ by a microtask, and `<picture>`'s sources don't have any state.

@zcorpan protested against the complicated algorithm as well, but we've discussed this and I think we've got a solution that's simple and contained enough to avoid these problems.

`<video>` has a long selection process that can be interfered with and exposes state that is observable by authors. `<picture>` takes a completely different approach where the core selection algorithm is completely isolated and atomic from authors' perspective.

[The algorithm](http://picture.responsiveimages.org/#update-source-set) only iterates through children. Whatever crazy stuff shadow DOM does to `Element.childNodes` is specced elsewhere and not `<picture>`'s problem. 

The selection algorithm cannot be interrupted, so it's guaranteed children cannot mutate during iteration. It's pretty simple - either `<source>` is in `childNodes` or not.

When something is mutated (and that can happen only between selection runs), then the selection's iteration is _repeated from the start_, with clean state, so `<picture>`'s sources aren't in any particular state. It's just that the same selection algorithm is re-run and picks some source from elements it finds matching at that time.

[Originally I've specced it](http://geekhood.net/picture-element.html#selection) to schedule (and coalesce) all updates to run on the next tick to avoid the selection algorithm potentially running at awkward times, and to make source selections even harder to observe by authors. I don't see anything like that in the current draft. @tabatkins @yoavweiss have I missed that in the new spec, or is that something you feel is unnecessary?

**Comment by Hixie** [comment]
The issue here isn't multiple elements (zcorpan has already accepted to take on the complexity of that). The issue here is reusing &lt;source>, which tangles the complexity of the media element algorithms with the complexity of the image stuff.

**Comment by kornelski** [comment]
Sorry, I still don't see where they're tangled :(

`<source>` in picture doesn't use anything from the [media element's](http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#media-element) interface/algorithms any more. 

The `<picture>` _used to_ be an `HTMLMediaElement` in the first version, but all of that has been discarded (that was way too complex and shouldn't be applied to images, I totally agree).

From perspective of `<video>` as far as I understand  `<picture><source></picture>` is not different than `<div><source></div>`. 

I'm assuming that even with all the shenanigans of Shadow DOM, it's not possible for `<source>` to be a child of `<video>` and `<picture>` at the same time (and even if they could, I think still both algorithms would work the same, since `<picture>` doesn't modify sources and doesn't care what `<video>` does).

It is possible to move `<source>` between `<picture>` and `<video>` element children, but it isn't a special case. From `<picture>` POV it's just a mutation that re-runs selection, and for `<video>` it's an insertion like any other (which is complex, but it has to be specced regardless as authors can move `<source>` to/from anywhere already).

_edit: oh, the setters for `src` and `type` are shared. Is that the tangling you mean?_

**Comment by Hixie** [comment]
If it's the same element, then they're tangled, even if it's just at an editorial level. For example, we now have to have some doubly-complicated content model for &lt;source>.

**Comment by kornelski** [comment]
You're right, on editorial level there's overelap. The [source section](http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#the-source-element) will need to be reorganized to explain both contexts the element can be in.

If that's the showstopper, then I can submit a patch :)

**Comment by Hixie** [comment]
I don't want a patch, I want someone who can commit to maintaining all the fallout for the next 5 years, so that I never have to pay the cost of this mistake.

**Comment by tabatkins** [comment]
I'm sorry, Hixie, but it really sounds like you're grasping.  There's a little bit of editorial work to address the content model (which is a validator issue), but none of the other issues you've hinted at are at all an issue; they're mostly you being confused about the original `<picture>` draft, or perhaps projecting the mistakes that `<audio>`/`<video>` made onto `<picture>` (incorrectly).

Can you explain again why you're opposed to this, now that you're aware that there is no tangling of media algorithms or odd timing issues or Shadow DOM issues?

@pornel:

> Originally I've specced it to schedule (and coalesce) all updates to run on the next tick to avoid the selection algorithm potentially running at awkward times, and to make source selections even harder to observe by authors. I don't see anything like that in the current draft. @tabatkins @yoavweiss have I missed that in the new spec, or is that something you feel is unnecessary?

I didn't copy from your spec when originally writing the current draft, so I wasn't even aware of it.  Feel free to raise it in a separate issue.

**Comment by Hixie** [comment]
If I'm "grasping", then it won't be much work, and it'll be no problem for someone else to maintain it.

**Comment by kornelski** [comment]
@tabatkins OK, added #152 about async source selection

**Comment by zcorpan** [comment]
@Hixie I'm happy to edit the `source` section. I've looked through the rest of the media section and I don't see anything that would be affected even if a `source` somehow were to have both a `picture` and a `video` parent at the same time.

**Comment by Hixie** [comment]
The problem is that the &lt;source> section is affected by the media section. It's a transitive closure thing.

**Comment by zcorpan** [comment]
Everything is intertwingled, so that reasoning would lead me to take over editing of the entire HTML spec.

In practice `source` changes so seldom that it won't be a problem for me to change it when you add/remove/change a feature to media elements that affects `source`.

**Comment by foolip** [comment]
What are you going to do with HTMLSourceElement.media? I'm about to remove it from Blink since it does nothing in the media element resource selection algorithm any longer...

**Comment by zcorpan** [comment]
@foolip http://picture.responsiveimages.org/#the-source-element

**Comment by yoavweiss** [comment]
@foolip - yeah, I don't think it's worth while removing it from Blink, only to add it back in a couple of weeks. Any related logic in HTMLMediaElement can be removed though (AFAICT, it already happened :) )

**Comment by foolip** [comment]
I need to remove the use counter anyway, so my plan is to remove HTMLMediaElement.media as well. I assume that the other picture-only attributes will live in a partial interface and be RuntimeEnabled for now, so just adding back the media attribute then seems like it will make for a cleaner history. Please object in the intent to remove if that's not acceptable: https://groups.google.com/a/chromium.org/d/msg/blink-dev/QuoobqOUCR0/3tNH-_gX6LwJ

**Comment by yoavweiss** [comment]
I don't intend to object. Adding it back behind a runtime flag sounds reasonable.
