### ISSUE TITLE
Why do we need a `<source-size-list>`?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#134]
Is there any use to the source-size-list vs. just maintaining a pair of (media condition, length), an error and an optional default value?

AFAICT, only matching media-conditions are added to the list,and then when finding the effective size, the first gets picked. Is there a benefit in maintaining the other media-conditions?

**Comment by zcorpan** [comment]
Yeah... I think it's enough with either an error or a (media condition, length) pair where media condition can be null (for the default value).

**Comment by yoavweiss** [comment]
Thinking about it some more, I'm not even sure we need to keep the "winning" media condition around.
AFAICT, the only output from sizes parsing is the effective size.
That means that we can simply keep the first length which pair media condition matches, and if there is none, the default one (the last one with a null media condition).

@tabatkins - WDYT?

**Comment by tabatkins** [comment]
It was just to make the conceptual model easier for me, so I could just parse all the strings into a useful structure, then operate on that structure at the point when I had all the information.

There's no use to having it in an actual implementation, and I'm fine with folding the "find the effective size" algorithm into the "parsing a sizes attribute" algorithm.

**Comment by yoavweiss** [comment]
OK, whatever works for you. As far as the impl go, I'll just do that as a black box that gets a string and the current env parameters, and outputs an effectiveSize, that's either the length that's the pair of the first media condition that matches, the last length that had no media condition, or the default 300px (or some other default value. @zcorpan discussed moving the default to "100%" on IRC, which kinda makes sense).

**Comment by zcorpan** [comment]
For the default value the spec picks the last value, but that seems like something that can be changed.

**Comment by zcorpan** [comment]
#137 changes this.
