### ISSUE TITLE
"Parse a sizes" missing percentage?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#138]
Looking at http://picture.responsiveimages.org/#parse-sizes-attr I've noticed that only `<length>` is permitted, and `<percentage>` is not.

Since the examples include percentages, I assume this is an omission, or that I'm missing something.

**Comment by yoavweiss** [comment]
As JohnS pointed out on IRC, calc is also missing from the definition

**Comment by zcorpan** [comment]
"[`calc()`] can be used wherever `<length>`, [etc] values are allowed."
http://dev.w3.org/csswg/css-values/#calc-notation

`<percentage>` is missing though.
