### ISSUE TITLE
Why do we allow `0x` descriptors?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#143]
It seems that the `x` descriptors are defined as non-negative integers. Shouldn't they be positive integers?

**Comment by yoavweiss** [comment]
I got it very wrong - `x` descriptors are floats!!!
Still, can we define them as positive floats?

**Comment by eeeps** [comment]
I'd be in favor of requiring `x` descriptors to be positive floats, and `w` descriptors to be positive integers. I don't see how either could be reasonably set to zero.

**Comment by zcorpan** [comment]
Per irc discussions, 0x is basically like `<img width=9999999999999999999999999999999999>` which is allowed. We should allow it and require an infinitely big image to be rendered, and implementations would have a limit (allowed by http://whatwg.org/C#hardwareLimitations ) on how big images can be. Normatively we don't need to add anything, but we could add a note somewhere saying something -- any suggestions?

For 0w, we could drop it during parsing, but I don't see any benefit in doing so and there's a risk of introducing bugs with changing the algorithm. However we can basically disallow it by requiring that it match the image's actual width.
