### ISSUE TITLE
Allow JavaScript to access 'src' chosen by the UA

### ISSUE THREAD

**Issue by tkadlec** [ResponsiveImagesCG/picture-element#148]
Looking at the current implementation of srcset in Chrome 34, there doesn't appear to be a way to access the `src` chosen by the UA via JavaScript. 

I've got a simple test case available here: http://timkadlec.com/test/images/srcset/.

The test is trying to access the `src` of the image using the image's `onload` event. The result is always the `src` specified in HTML, regardless of whether or not it's actually requested and used.  My assumption was that the `src` should be updated to reflect what the UA is actually selecting. 

Any thoughts?

**Comment by tkadlec** [comment]
Also, I believe  (per @Wilto) that the `src` would indeed be updated by definition for `picture`. Seems `srcset` alone should match that behavior.

**Comment by tabatkins** [comment]
The current idea is to expose it as `.currentSrc`, leaving `.src` alone as reflecting the `src=''` attribute.  I think that's better, because I prefer when properties with the same name as attributes Just Work®.

**Comment by yoavweiss** [comment]
:+1:  to leaving poor src alone :)

**Comment by Wilto** [comment]
Sounds good to me. +1.

**Comment by tkadlec** [comment]
I was unaware of this, but totally dig it. :+1:

I really like when issues turn out to be non-issues. I'm gonna go ahead and close since it sounds like this has already been though through and I just missed it.

**Comment by Wilto** [comment]
(Reopening until we get this into the spec.)

**Comment by uniqname** [comment]
To clarify, would the `currentSrc` be a property on the `picture` node or only on the controlling `img` node?

**Comment by tabatkins** [comment]
The `<img>`.  It doesn't make sense to put it on `<picture>`, since `<img>` can have `srcset=''` all by itself.

**Comment by zcorpan** [comment]
What's the use case?

**Comment by yoavweiss** [comment]
One use case I can think of would be enabling authors to detect which art-directed image was picked (without recreating the selection algo in JS), and plan dynamic modifications (animations, etc) around that.

**Comment by zcorpan** [comment]
https://github.com/ResponsiveImagesCG/picture-element/pull/149 fixes this.

I think we didn't do a thorough job of thinking about the use cases before adding something to the spec, but at least `video` already has `currentSrc` so authors may come to expect that `img` also has it, and it's cheap and it lets us see what authors are using it for, if anything, in a few years so we can evaluate if there's something else needed.

**Comment by marcoscaceres** [comment]
I'm not comfortable with adding this, tbw. There doesn't seem to be a strong use case for it.

**Comment by tabatkins** [comment]
I can definitely see use-cases based around advanced manipulations of the page.  It's not uncommon that doing complicated animations requires duplicating part of the content temporarily.  You could duplicate the entire <picture> element, sure, but that prevents the image from being used in CSS and whatnot.  (Also, it would be _entirely_ reasonable for the image selection algorithm to involve some hysteresis, so duplicating a <picture> could actually choose a different url!)

Having the chosen src URL lets authors do that kind of thing easily.  And if there are any other reasons for knowing which `<source>` was picked, for example, knowing the URL lets you determine that too (assuming you don't reuse URLs, which there's no reason to do).

**Comment by uniqname** [comment]
I've run into some frustrations with not being able to easily or accurately determine what font is being used from a given font-stack in css. I can foresee similar frustrations when trying to suss out the cause of a problem or outcome with respect to source selection on `<picture>` or `<img>`.

**Comment by marcoscaceres** [comment]
@tabatkins, I see. 

@uniqname sure, but what you are saying still sounds like something that could be solved by a developer tool. 

I'm ok to keep it for now, just want to make sure we clearly separate the API from things that are best handled by dev tools (particularly for debugging). Of course, being able to automate tests to make sure the right resource is being selected via JS is a "nice to have".
