### ISSUE TITLE
width descriptor in srcset and picture specs

### ISSUE THREAD

**Issue by waldbaerkoch** [ResponsiveImagesCG/picture-element#154]
From reading http://picture.responsiveimages.org/ and http://www.w3.org/html/wg/drafts/srcset/w3c-srcset/ I get the impression that the width descriptor in the srcset attribute in both specs represents something different. In http://www.w3.org/html/wg/drafts/srcset/w3c-srcset/ it means maximum viewport width in CSS pixels. In http://picture.responsiveimages.org it is the intrinsic width of the image resource in device pixels.
Is this a problem?

**Comment by tabatkins** [comment]
Yes, the "extended srcset syntax" from the WHATWG spec (using the w/h descriptors) was entirely dropped.  Nobody had implemented it.

The `<picture>` spec picked a similar syntax for something different.

This confusion will be cleared up when the `<picture>` spec is merged into HTML proper.

(Also, don't read the W3C drafts. They're generally obsolete.  Read the [WHATWG spec](http://whatwg.org/html) instead.)
