### ISSUE TITLE
Clearer spec for currentSrc

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#155]
I think the selection algorithm should set currentSrc so that it's clearer when exactly it gets set and what to. (Also make sure it's the resolved URL to match media elements.)

**Comment by zcorpan** [comment]
@yoavweiss and I discussed this a bit on IRC today. For environment change case, we probably want to wait with updating currentSrc until the task that fires the "load" event, since it's supposed to be transparent if the load fails. So possibly we should just make currentSrc always update at the same time as we fire "load" (or change the image to the broken state).

`<video>` changes currentSrc at selection-time (but it doesn't change stuff based on environment changes).

If there are use cases here one way or the other, let's hear it.

**Comment by yoavweiss** [comment]
@zcorpan - Since no one seems to have a strong opinion on the matter, I think we should spec the behavior to the one you suggested, with currentSrc updated right before the load event fires (so that it can be examined from inside the load event).

I'll start working on a patch that makes that change in the Blink implementation.

**Comment by zcorpan** [comment]
The default value should also be the empty string instead of null, for consistency with video currentSrc.

**Comment by zcorpan** [comment]
Upon further consideration I think the best thing would be to update currentSrc when the new image is swapped in (which is when the dimensions are available), so that it's in sync with the image being rendered and with .width .height .naturalWidth .naturalHeight.

**Comment by yoavweiss** [comment]
I guess that makes sense. That way currentSrc will be aligned with the image displayed to the user, rather than the image that is going to be displayed to the user.

**Comment by yoavweiss** [comment]
Can we have a link to the definition of "current request"? I'm having trouble finding it.
I'd also like to link to "currentSrc should be exposed only after the image dimensions are known" from the code that does that. Is it the "current request" definition?

**Comment by zcorpan** [comment]
@Hixie hasn't synced yet so I guess that's why you don't find it. :-)

Technically it's "update the image data" and the "environment changes" that modify or swap out the "current request".
