### ISSUE TITLE
Viewport dimensions of "orphan" images

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#156]
How should we define the viewport dimensions according to which `sizes` and `media` should be calculated for "orphan" images? By "orphan" I mean:
- Images that were not yet added to the document
- Images that were set after the parent document have died
- Images loaded since their xhtml document was fetched via XHR
- Images inside a [created document](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation.createHTMLDocument).
- Other?

**Comment by yoavweiss** [comment]
> Images that were not yet added to the document

These may not be an issue, since they're supposed to be associated with the document (even if not yet inserted into it). Therefore, they can relate to the document's viewport.
Images that are innerHTMLed into elements that are not inserted into the document may not be associated with it, though.

**Comment by tabatkins** [comment]
0x0

**Comment by yoavweiss** [comment]
> 0x0

That may result in double downloads, once these resources are associated with a different document, or when their document gets a frame. On the other hand, since these are edge cases (perhaps besides the innerHTMLed images, which I'm not sure is not a bug), we may not care so much about that.

So, I'm cool with saying that.

**Comment by tabatkins** [comment]
eseidel talked to me yesterday, and he suggested that as much as possible, we try to associate the image with a useful document.  I suppose for script-created ones that's the document that's running the script.  I'd ask Anne or Hixie about what the correct wording is for that kind of thing, if you want to pursue it.

**Comment by tabatkins** [comment]
And what's this about innerHTML?

**Comment by yoavweiss** [comment]
Looking back at the [test](https://github.com/yoavweiss/Blink/blob/master/LayoutTests/fast/dom/HTMLTemplateElement/innerHTML-inert.html) that made me think this is an issue, I've got it wrong. It's most probably the inert HTMLImageElement which document doesn't have a frame.

**Comment by yoavweiss** [comment]
@tabatkins Talking to @esprehn on #blink, it seems that what you suggest may be difficult to implement. HTMLImageElement is not aware of the script that created it. To quote @esprehn: "we shouldn't introduce APIs where the constructor has to do some magical script execution context lookup". I agree with that, especially since the benefit from doing that (avoiding a double download in some edge cases) is most probably low.

**Comment by tabatkins** [comment]
I've got no problem with that.  0x0 it is.  

Anyway, 0x0 will generally select the smallest resource (and we could special-case it to make sure of that, if we felt like it), so the double download is even less of a big deal.
