### ISSUE TITLE
parse sizes algorithm bug

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#158]
In http://picture.responsiveimages.org/#parse-sizes-attr step 3, we should also handle the case where there are no components values remaining in unparsed size

**Comment by zcorpan** [comment]
Do you want step 3 to say the same thing as step 1?

**Comment by yoavweiss** [comment]
No. Consider "100px   ":
It's tokenized into DimensionToken, WhitespaceToken, WhitespaceToken.
Step 1 removes the trailing WhitespaceToken, leaving unparsed sizes as DimensionToken.
Step 2 sets size to be the DimensionToken's value. Unparsed sizes is now empty.
IMO, Step 3 should return now, but according to the current algo it doesn't, since the remaining component values (which there aren't any) are not whitespace tokens.

**Comment by zcorpan** [comment]
Right. I meant... do you want step 3 to say this?

"Remove all consecutive <whitespace-token>s from the end of unparsed size. If unparsed size is now empty, return size and exit this algorithm."

That would make the step return size for your case, and also for " 100px" (WhitespaceToken, DimensionToken)

**Comment by yoavweiss** [comment]
OK,  so I misunderstood you...
Same as step 1 would be great :)

**Comment by tabatkins** [comment]
Step 3 already says what you want.  All remaining component values are not whitespace tokens (because there aren't any component values left).

It's a vacuous resolution to the conditional, is all.

**Comment by zcorpan** [comment]
I first read it that way also @tabatkins but @yoavweiss didn't which means that the spec isn't super-clear. The change I suggested would make it clearer, right?

**Comment by tabatkins** [comment]
Yes, I'm fine with changing it; vacuous conditionals aren't really obvious to most people. ^_^

I was just clarifying that this isn't a behavior change, just a restatement for clarity.
