### ISSUE TITLE
Define which viewport/frame is sizes evaluated against

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#159]
According to https://github.com/ResponsiveImagesCG/picture-element/issues/156 , we want sizes to be evaluated against a 0x0 viewport in the case that the img request is created in a context that has no frame.

Do we need to specify that? (possibly beyond viewport related values)

**Comment by zcorpan** [comment]
That's already defined in http://www.whatwg.org/specs/web-apps/current-work/multipage/rendering.html#the-page

"If a browsing context is not being rendered, it is expected to have a viewport with zero width and zero height."

A document could also be without a browsing context, but we don't fetch stuff for such documents anyway (there's no event loop IIRC).

**Comment by yoavweiss** [comment]
Awesome! Closing then.
