### ISSUE TITLE
Clarify/Define the accessibility model of the <picture> element

### ISSUE THREAD

**Issue by komputist** [ResponsiveImagesCG/picture-element#16]
What is the accessibility model of the picture element?

A subquestion of this is: What is the ARIA role of the <picture> element. Is it, for instance, img? (<picture role="img" >) If yes, then the answer will probably have implications for the accessibility model, since the fallback of an element of role="img" by default is that the content is not rendered to AT users unless the author uses aria-labelledby/aria-describedby.

Currently, the accessibility model is hinted  only in the 'Example of usage' section, where it is evident that the thought is that the fallback will serve as accessible content.

To let the a11y model rely on fallback content has several implications:
 (A) The implication of the 'img' role ought to mean that picture’s role cannot (by default) be 'img' since such a think would hide the fallback from being rendered to AT users.
 (B) When accessible content is needed, then authors would be obligued to provde fallback content in the form of an <img> element with a non-empty alt attribute - or by providing other fallback elements.

**Comment by anselmh** [comment]
Thanks for asking, you are mentioning a valid point.

Also the spec does not cover this topic really good for now. It just says 

> …while also potentially providing better accessibility than the existing <code>img</code> element

This should be clarified in spec.

**Comment by marcoscaceres** [comment]
Agreed. We are waiting to see where we go with converging the srcset and picture specs before we proceed further, but the above information is super helpful. If we continue forward with `picture`` then we will work with the accessibility task force to make sure we have the right text in place.

**Comment by LJWatson** [comment]
Could the alt attrib be applied to the picture element?

One of the advantages of srcset is that it's applied to the img, which can also take the alt attrib. This means that from an accessibility point of view the model is well established, legacy support is preserved, and the alternate text description is unequivocally associated with the image.

The association between the picture element and the accessible text seems much more tenuous. Could a child paragraph of the picture element be a conformance requirement do you think?

Until the nature of the accessible content is better defined, it's difficult to say, but I wonder whether authors will find the introduction of another mechanism for providing a text description confusing?

Happy to reach out from the HTML-A11y TF to help if I can be of use?

**Comment by anselmh** [comment]
On Thursday, 7. February 2013 at 13:17, LjWatson wrote:

> Could the alt attrib be applied to the picture element?

No, this has been discussed several times but it does not make too much sense.  
Better use the alt text as child element of picture as it's shown in the current specification.
You surely can say in spec that this is "required" afaik.

**Comment by yoavweiss** [comment]
@LjWatson - Thanks for reaching out from the A11Y TF :)
I'm not an accessibility guy, and I'm not sure regarding the history that led to the current a11y model of the `<picture>` element, but AFAIK the intention was to provide a better alternative text than a simple `alt` attribute.
The example that came up in that context in TPAC was to provide a `<table>` as an alternative text when the image's content is a chart.

I'm sure Steve Faulkner and @marcoscaceres can shed more light on the reasons we went with a child element for alternative text rather than an `alt` attribute.

**Comment by marcoscaceres** [comment]
If we can get some traction with `<picture>` then we want to work with the a11y TF to add the best accessibility model we can. It's certainly one of our stated requirements - but as @yoavweiss, said, we are a bit timid about adding those features without first working through them with the a11y TF. 

Having said that, there are a ton of documented issues with alt (see http://www.w3.org/html/wg/wiki/IssueAltAttribute). Authors have a hard time understanding how to use it properly, it does not support internationalization very well, etc. Other solutions, like wrapping a `picture` in a figure and using `figcaption` seem to provide better context gives images meaning (when appropriate). @yoavweiss also mentioned using a `table` where  appropriate, etc.

**Comment by Wilto** [comment]
Also, there was some concern with authors needing to specify an `alt` on both `picture` and the fallback content (typically `img`).

With the fallback content as the a11y content, authors would only need to specify an `alt` on the `img` to get that same basic level of accessibility in browsers that do support `picture`—but, with the potential for richer a11y/fallback content through specifying markup like (as @marcoscaceres mentions above) a table for an infographic, or ordered list for an image of a flowchart. It stands to benefit users in non-supporting browsers and users navigating by way of assistive tech. Steve Faulkner and Laura Carlson were both involved in those discussions, though it was a while back—I’ll see if I can dig the messages up in the archives later on today.

**Comment by marcoscaceres** [comment]
This relates to #19. Hopefully will get those examples soon from @aarongustafson.

**Comment by LJWatson** [comment]
Thanks Yoav J

“I'm not an accessibility guy, and I'm not sure regarding the history that led to the current a11y model of the <picture> element, but AFAIK the intention was to provide a better alternative text than a simple alt attribute.”

If this is the intention, it would be good to include something about it in the spec. Perhaps a more illustrative example?

I’m curious about the intended visibility of the accessible content though. Is the thought that it would be visible unless the author styled it otherwise?

Assuming for the moment that’s the case, legacy support is going to be a bit tricky. Someone using a screen reader and a browser that doesn’t support picture, will hear both the alt of the img and the accessible text for the picture.

No immediate answers I’m afraid, just throwing some thoughts out for consideration.

**Comment by marcoscaceres** [comment]
@LjWatson, please feel free to file additional bugs on the spec on what examples you would like to see (see, for example, #19). We will be happy to add those examples.

**Comment by komputist** [comment]
The alternative to <code>picture</code>, the srcset attribute on the <code>img</code> element, does have a, not perfect, but clear accessibility story. That speaks to srcset’s advantage.

To require <code>img</code> as fallback for <code>picture</code>, is not an advantage to authors, I believe.

Yes, <code>picture</code> has the _potential_ for a _richer_ accessibility story than <code>img</code>. But then you need to take out that potential - and make it an advantage. Or else it won't matter.

But <code>picture</code> also has the potential of becoming worse the <code>img</code>, e.g. if it just hides the real, accessible content (namely the <code>img</code> in the fallback). 

If you think that richer (more "respsonsive"?) alternative text is one of the use cases that <code>picture</code> is going to solve, then why not describe it in in http://usecases.responsiveimages.org ? Right now, that document doesn't say anything at all about alternative text. 

Regarding the A11Y communitiy: Listening to it, yes. But _waiting_ for it  to chime in — or waiting for traction with regard to the <code>picture</code> element itself, would not have been my strategy.

**Comment by tabatkins** [comment]
`<picture>` now just drives an `<img>`, so this is moot.
