### ISSUE TITLE
Forbidding non-source children above img

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#167]
I've been thinking about the handling of picture's selection algo in the preloader (where we have no DOM tree), and it seems like current algo would require me to maintain a stack of previously seen source URLs, for cases like:

```
<picture>
  <source>
  <source>
  <picture>
     <source>
     <img>
  </picture>
  <img>
</picture>
```

Since I don't think this is something we should actively support (no one should use picture that way), I think we can change the selection algorithm to exit if it hits anything that's not a `source` or the `img` element itself.
So something like changing step 3.2 of [updating the source set](http://picture.responsiveimages.org/#update-source-set) to be "if child is not a <source> element, exit this algorithm".

On the one hand, it's less fault tolerant, but on the other, it'd rid us of tons of edge cases, and would prevent the display of multiple images under a single <picture> element.

@zcorpan & @tabatkins - what do you think?

**Comment by tabatkins** [comment]
This sounds completely fine to me, but as zcorpan noted, it means more monitoring of changes for the <img>, as a previously-valid <img> might be invalidated by you inserting any element before it.

If you're fine with that, I am too.

**Comment by yoavweiss** [comment]
I think that even without this change we'd need to re-run children `img` selection algo when other children are added to the parent (see https://github.com/ResponsiveImagesCG/picture-element/issues/168), as they may be `<source>` elements and impact the selected source.

Since this would significantly lower preloader-time complexity, I think it's well worth changing it.

**Comment by zcorpan** [comment]
You can exit in the preloader when seeing something that's not `source` or `img` -- it will only fail to preload images with invalid markup, which seems OK. But I don't think we should change the spec's algorithm here because I've seen e.g. `<br>`s between `<source>`s in `<video>` (IIRC some blog software being "smart" and converting newlines to `<br>`), and I think it would be bad not to support that.

**Comment by yoavweiss** [comment]
I'd really hate to have the preloaded ignore resources within invalid
markup. Maybe exit the algorithm when one of the children is picture? (So
allow brs but prevent nested picture elements)

**Comment by zcorpan** [comment]
It wouldn't help you with `<picture><video><source>` or `<picture><p><source>`. But I guess you could let through any of the void elements. http://www.whatwg.org/specs/web-apps/current-work/multipage/the-end.html#serializing-html-fragments has a list (area, base, basefont, bgsound, br, col, embed, frame, hr, img, input, keygen, link, menuitem, meta, param, source, track or wbr)

**Comment by zcorpan** [comment]
OTOH, if you do preload a URL that turns out to be a wasted fetch, that's not the end of the world, either, and happens already if a script does a `document.write` that changes the meaning of the following markup. It might also already be possible to trick the preload scanner with weird markup like `<svg><style/></svg><img>` or some such.

**Comment by yoavweiss** [comment]
> It wouldn't help you with <picture><video><source> or <picture><p><source>. But I guess you could let through any of the void elements. http://www.whatwg.org/specs/web-apps/current-work/multipage/the-end.html#serializing-html-fragments has a list (area, base, basefont, bgsound, br, col, embed, frame, hr, img, input, keygen, link, menuitem, meta, param, source, track or wbr)

`<picture><source><video><source></video><img></picture>` doesn't bother me all that much from a preloader perspective, but e.g. `<picture><source><div><picture><source><img></picture></div><img></picture>` would...
So, you're right, we can forbid anything without a self closing tag. I think that'd be best.

> OTOH, if you do preload a URL that turns out to be a wasted fetch, that's not the end of the world, either, and happens already if a script does a document.write that changes the meaning of the following markup. It might also already be possible to trick the preload scanner with weird markup like <svg><style/></svg><img> or some such.

I know, but it's not ideal, and since there's no reason to allow nested elements inside picture (at least not above `<img>`), I think the best way to go would be to avoid them altogether.

**Comment by zcorpan** [comment]
OK, so no change to the spec here?

**Comment by yoavweiss** [comment]
On the contrary. I would like to see a spec change (unless you think it bares further complications):
-  Changing step 3.2 of "updating the source set" to be something like "if child is not a void element, exit this algorithm".
- Add to the mutation events an event stating that an addition of a non void element as a previous sibling also triggers a source update.

**Comment by Wilto** [comment]
I’m for forbidding non-void children here, based on a read through the thread—I think it’s a safer bet to start with the simplest case (disallowing crazy nesting or unrelated elements in `picture`), and reconsider if anyone comes along with a compelling case _for_ nesting and whatnot.

Side-note: Picturefill is using a `video` inside `picture` (in an IE9-only conditional comment) to prevent IE9 from stripping out the `source` elements inside an unrecognized context—I assume that approach will still be viable either way, yeah?

**Comment by yoavweiss** [comment]
On second thought, my proposal is not ideal, in the sense that multiple `img` element, or element that follow invalid nesting would "disappear". That's likely to be confusing ("where the F**\* did that image go?").

A better alternative might be to detect non-void children, and if encountered, let the `<img>` that initiated the source selection ('el') just load its own srcset or src.

That way, if the `img` is there by mistake, the author can catch and get rid of it, and if it's there on purpose, it shows something, rather than nothing.

As a bonus, I think it'd simplify impl even further.

WDYT?

**Comment by Wilto** [comment]
Ah, I think I misread—I assumed that breaking out of the selection algo meant that the remaining `img` would do their own thing as usual. That’s definitely what I’d expect, authorship-wise.

**Comment by zcorpan** [comment]
That seems bad for future extensions. We wouldn't be able to introduce a new element and put it into `<picture>` (before the `<img>`), e.g. like `<video>` did with `<track>`.

**Comment by yoavweiss** [comment]
Do we expect such extensions to be introduced and impact source selection
(otherwise they can be placed after the 'img')?
Do you think this possible extensibility is worth the extra implementation
complexity?

**Comment by zcorpan** [comment]
I don't want to close the door on introducing elements before the `img`, whether the new thing impacts source selection or not.

I don't see the proposed change as being a clear-cut simplification in implementation complexity. See https://github.com/ResponsiveImagesCG/picture-element/issues/165#issuecomment-41477744

Also, if I understand correctly, the current spec is only complex for you in the prescanner because Blink doesn't maintain a stack of open elements. This isn't something that is true in all implementations -- IIRC Gecko will run the whole HTML parser speculatively.

**Comment by zcorpan** [comment]
Also I disagree with the premise that the prescanner needs to have 100% fidelity. (It already doesn't.)

**Comment by zcorpan** [comment]
c.f. https://github.com/ResponsiveImagesCG/picture-element/issues/172

**Comment by yoavweiss** [comment]
I agree that script/template should be allowed. Closing.
