### ISSUE TITLE
Should insertion of children elements into picture trigger source selection in existing children?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#168]
e.g. if a source element was added as a first child to

```
<picture>
  <img>
</picture>
```

the `<img>` should re-run its source selection algorithm, right?

If so, I think we need to define it.

**Comment by zcorpan** [comment]
It's defined already.

http://picture.responsiveimages.org/#relevant-mutations
http://picture.responsiveimages.org/#issue-58bdc3bf

**Comment by yoavweiss** [comment]
Somehow missed it. Thanks!
