### ISSUE TITLE
Default styles for non-img children of picture

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#170]
I think we should add a note (@tabatkins indicated a non-normative note is typical) with suggested styling for non-`img` children of `picture`. If we add some styles that visually hide these children, but still expose them to screenreaders and other AT, it could provide better accessibility options than `alt` alone.

E.g.

```
<picture>
    <source ... />
    <source ... />
    <img alt="An infographic with statistics about heart disease" />
    <table>
    <!-- all actual stats can go here -->
    </table>
</picture>
```

The default styles could be something similar to what [HTML5 Boilerplate](https://github.com/h5bp/html5-boilerplate/blob/master/css/main.css) or other libraries use for visually hidden but AT-exposed content, e.g.:

```
picture *:not(img) {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}
```

**Comment by zcorpan** [comment]
Default rendering is defined in HTML's rendering section.

The suggestion here would have bad rendering in legacy UAs, they would get both the image and the table.

How would you make the table show up when the image shows its fallback content?

Alternatively, if you only care about AT, why not use `aria-describedby` instead?

**Comment by zcorpan** [comment]
The suggested styling also fails for text without elements.
`<picture><img ...> foo </picture>`

**Comment by nwtn** [comment]
I agree with @zcorpan's points above. After a discussion on IRC, I'm ready to close this issue out.

Basically:
- this type of content is better off being _outside_ of `picture`, but associated with the `img` using something like `aria-describedby` or a `figcaption`
- if authors choose to include non-`img` content under `picture` (but after `img`), it will be invalid, but (for now) won't break anything
  - the content will be visible, but can be hidden with CSS by the author
  - similarly, the content will be exposed to AT, but can be hidden by the author
  - the content will not be specifically associated with the `img`, but could be associated with `img` using `aria-describedby`
