### ISSUE TITLE
Thoughts on shipping sizes & srcset 'w'?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#175]
Assuming that the [absolute currentSrc](https://codereview.chromium.org/290803002/) change will land soon, the work on sizes/srcset seems to be done.

Do we envision any backward incomaptible changes to the spec in these areas? 

If not, does anyone object that I'd try to ship the feature in Chrome 37? (So that it'd hit stable mid-August)

**Comment by zcorpan** [comment]
https://github.com/ResponsiveImagesCG/picture-element/issues?labels=behavior-change&page=1&state=open I see #166 and #152

**Comment by yoavweiss** [comment]
If we want to try to ship sizes+srcsetW at Chrome 37, we need to finalize these issues by the end of month (give or take a few days).

**Comment by yoavweiss** [comment]
1 down, 1 to go... :)

**Comment by yoavweiss** [comment]
Since both these issues are now closed, I intend to send an "intent to ship" in the next few days, unless anyone has string objections. If someone does, please re-open.

**Comment by Wilto** [comment]
![](http://yodaismybackpack.files.wordpress.com/2013/02/engage.gif)
