### ISSUE TITLE
srcset parser should look for 'h' descriptors

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#176]
Since we anticipate adding a `h` descriptor in the future (#85 #86) I think we should make the parser do the right thing now so that we don't get into a situation where Web compat expects `2x 100h` to not drop the entire candidate (like we currently do with `2x 100w`).

Step 12, add/change
[[
...
Let future-compat-h be absent.
...
(for "x" token)
If width, future-compat-h and density are not all absent, then let error be yes.
...
If the token consists of a valid non-negative integer followed by a "h" (U+0068 LATIN SMALL LETTER H) character
If future-compat-h and density are not both absent, let error be yes.
Apply the rules for parsing non-negative integers to the token. If the result is zero, let error be yes. Otherwise, let future-compat-h be the result.
]]

The only change here would be that specifying both `h` and `x` makes the candidate be dropped. The `h` descriptor is otherwise ignored like today.

**Comment by yoavweiss** [comment]
Doesn't that mean that we need to be able to predict whatever descriptors we may want to add in the future?

**Comment by zcorpan** [comment]
No, we just predict that `h` is likely to be added in the future and that it's likely we want it to have the same parsing behavior as `w`. For anything else we don't know anything and the default behavior of dropping unknown descriptors seems reasonable to me.
