### ISSUE TITLE
section 5 is missing the type-attribute and its behavior

### ISSUE THREAD

**Issue by anselmh** [ResponsiveImagesCG/picture-element#18]
Section 5 of the spec says " Algorithm for deriving the source image" but it misses the behavior if source has a type attribute given.

I think it should be described as following:

> If the type attribute is provided with an unsupported type to the User Agent, source should be ignored. User Agent only fetches sources that are applying the media query and are of a supported mime type.

**Comment by marcoscaceres** [comment]
You are correct, but the wording above is not quite right. I need to investigate this a little bit more. I'll update the text in the next few days.

**Comment by yoavweiss** [comment]
@marcoscaceres Can we close that issue with commit https://github.com/ResponsiveImagesCG/picture-element/commit/dbdfb08da9f59afaaa41576ca9f7ed6884880b3c ?

**Comment by marcoscaceres** [comment]
Closing. We might need to revise this further, but what is there now is ok.
