### ISSUE TITLE
Remove leading comma in URL?

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#182]
We're now trimming off trailing commas in URLs in srcset, but should we do that in the beginning also?

srcset=",foo 2x, ,bar"

Do we want the URLs to be "foo" and "bar" or ",foo" and ",bar"?

If we want the former, the fix is easy; instead of "skip whitespace" at the start of the splitting loop, we say "collect a sequence of characters that are space characters or commas".

**Comment by yoavweiss** [comment]
Most definitely the former
