### ISSUE TITLE
Negative 'x' descriptors

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#183]
I noticed that the srcset parser seems to happily accept negative x descriptors. I guess we should set "error" to "yes" in that case?

**Comment by yoavweiss** [comment]
Yes, definitely

**Comment by Wilto** [comment]
Picturefill and (I think) @yoavweiss’ native stuff behaves this way, yeah?

**Comment by yoavweiss** [comment]
The implementation in Blink treats negative x descriptors as invalid.
