### ISSUE TITLE
Add example of how to use figure, figcaption, and picture together

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/picture-element#19]
Need to add example to the spec of how to use figure, figcaption, and picture together.

**Comment by aarongustafson** [comment]
I can tackle this later today if you like. Just let me know.

**Comment by marcoscaceres** [comment]
go for it! Send a pull request or markup. Whatever is easiest

**Comment by aarongustafson** [comment]
Will do.

**Comment by yoavweiss** [comment]
@marcoscaceres @aarongustafson Was this issue resolved?

**Comment by marcoscaceres** [comment]
Don't think so. @aarongustafson, would still appreciate this example if you have time.

**Comment by aarongustafson** [comment]
Yes, apologies. Work got in the way.
