### ISSUE TITLE
Special case candidates with no descriptors?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#190]
In current srcset implementation, the handling of candidates with invalid descriptors (e.g. "1x.gif 1q" is different than the handling of candidates with no descriptors (e.g. "1x.gif"). Candidates with only invalid descriptors are ignored, rather than picked as candidates with default density.

I inherited this behavior from the early WebKit implementation, and since it was backed up by tests, I assumed it aligns with the spec. From what I can tell now, it isn't. (and I don't think it ever was)

So, do we want to keep that behavior? Does it make sense?

Personally, I'm not sure it does, and would be happy to dump it.

**Comment by zcorpan** [comment]
I think we should keep the spec as is. It seems better for future extensions.
