### ISSUE TITLE
Should 0x descriptor be allowed for authors or not?

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#191]
Currently 0x gets parsed OK but authors must use something greater than 0. We've resolved on the parsing behavior already, this bug is just about authoring conformance.

@tabatkins WDYT, is it fine to be different here or do you want the rules to match up?

**Comment by tabatkins** [comment]
I am absolutely fine (strongly in favor, even) of authoring conformance criteria mandating things for authors that are different from the conformance criteria for implementors.  We have to spec all kinds of weird things to handle legacy or edge-case behavior that has no relevance to authors, and in fact would be a bad idea for them to try and deal with.  Using conformance criteria as a clear signal of "don't worry, nothing to see here, just dotting our i's and crossing our t's" is a Good Thing©.

So yes, keep the current conformance criteria that mandates authors should not use 0x, but requires impls to parse 0x.  It is precisely the "corner-case handling" behavior I just talked about.
