### ISSUE TITLE
Expand on “Relationship to `srcset`” section

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#194]
Thinking I should add a little bit to the last line of http://picture.responsiveimages.org/#relationship-to-srcset. I know the W3C `srcset` doc is gonna end up getting replaced after we merge our stuff into the WHATWG spec, but there’s still a lot of confusion about which is which for right now.

Worth doing, we think?

**Comment by nwtn** [comment]
+1
i've seen a lot of confusion about this. even if it's temporary, i think it could help ease the transition.

**Comment by zcorpan** [comment]
Sure. The srcset spec is actually going to be a subset of the picture spec.

**Comment by Wilto** [comment]
Just got an update from @zcorpan on IRC: http://ircbot.responsiveimages.org/bot/log/respimg/2014-06-02#T74145

@hober, you got a rough timeline in mind? Trying to figure out whether it’s worth writing a little something to clarify, here. Also, does this mean we should work on breaking the `srcset` sections of picture.responsiveimages.org into a stand-alone document? I can get started on that whenever, if need be.

**Comment by hober** [comment]
I told the chairs I'd get to it after WWDC, so hopefully during the week of 9 June.

**Comment by Wilto** [comment]
Ref. 194f19d400b2d6e8bb98dace49a595d8c067097f; leaving this issue open until we update the W3C version.

**Comment by Wilto** [comment]
Check that; filing a new issue for updating the W3C fork.
