### ISSUE TITLE
Drag and drop <img> with a <picture> parent

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#198]
Should we make dragging an `<img>` with a `<picture>` parent actually drag the `<picture>`? `<img>`s are draggable by default so if you want to make `<picture>` draggable today you'd have to specify draggable=true on the picture _and_ draggable=false on the `<img>`.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3053 - contenteditable (the picture gets dropped in Chrome)

http://www.w3schools.com/html/tryit.asp?filename=tryhtml5_draganddrop - add `<picture>` around the `<img>`, drag the image, inspect element (the picture is left behind, resulting in an invalid DOM)

**Comment by zcorpan** [comment]
Maybe change:

[[
Otherwise, the element's draggable content attribute has the state auto. If the element is an img element, an object element that represents an image, or an a element with an href content attribute, the draggable IDL attribute must return true; otherwise, the draggable IDL attribute must return false.
]]

to

[[
Otherwise, the element's draggable content attribute has the state auto. If the element is an img element that does not have a picture parent element, a picture element, an object element that represents an image, or an a element with an href content attribute, the draggable IDL attribute must return true; otherwise, the draggable IDL attribute must return false.
]]

http://www.whatwg.org/specs/web-apps/current-work/multipage/dnd.html#dom-draggable

**Comment by mathiasbynens** [comment]
The suggested change seems more sensible and much less surprising for web developers. SGTM.

**Comment by zcorpan** [comment]
So the proposed change would work fine for valid cases but might get confusing results if a page does something stupid like wrap the whole page in `<picture>` which would make the whole page draggable (this could reasonably happen if you typoed the end tag). However I can't come up with a sane way to solve that.

**Comment by mathiasbynens** [comment]
It makes sense to optimize for the common case, not the stupid case.

**Comment by Wilto** [comment]
Took a little thinking to come around to it, but I’m with you guys on this one. No ideas on how to deal with the “`picture` left open” case, though.

**Comment by jonathantneal** [comment]
This situation is very similar to how developers used `<object>` and `<p>` within `<video>` and `<canvas>` elements.

Within `<picture>`, `<img>` is fallback content. I’m told it’s required fallback content, at that.

Fallback content is contextual and dependent on its parent, so I would expect any selection of `<img>` to actually select `<picture>`.

**Comment by tabatkins** [comment]
Well, no, `<img>` isn't fallback content.  It was in the misty past, but now `<img>` is the thing that's actually displayed at all times; the `<picture>` is just a controller for the contained `<img>`, not something which displays on its own and has "fallback".

But still, the `<img>` _is_ intimately connected with its `<picture>` parent, so your point stands.

**Comment by jonathantneal** [comment]
Thanks for the education, @tabatkins.

**Comment by zcorpan** [comment]
This change screwed up the drag store, and fixing that seems like it will be a source of bugs. So I think it's better to revert the change here.
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26024
