### ISSUE TITLE
The behavior of picture's `src` attribute is unclear

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#2]
We need to define the behavior with regard to `<picture>`'s `src` attribute:
- What should be done when `src` is present and no `<source>` matches - probably load & display that `src` if we want to match the `<video>` tag behavior
- What should be done when `src` and a matching `source` are both present - ???

**Comment by marcoscaceres** [comment]
in case 2, if src is present, `<source>`s are ignored. I think that's what video does.

**Comment by marcoscaceres** [comment]
(sorry, pressed close and comment by accident!)

**Comment by remi-grumeau** [comment]
Agree

**Comment by anselmh** [comment]
See here how it should be done: 
- http://dev.w3.org/html5/spec/single-page.html#the-source-element
- http://dev.w3.org/html5/spec/single-page.html#concept-media-load-algorithm

**Comment by marcoscaceres** [comment]
@anselmh unfortunately, the [resource selection algorithm](http://dev.w3.org/html5/spec/single-page.html#concept-media-load-algorithm) doesn't apply here (and images are not media resources as per HTML). We need a modified version of the [process the image candidates](http://dev.w3.org/html5/srcset/#processing-the-image-candidates-0) algorithm.

**Comment by marcoscaceres** [comment]
@anselmh if you want to check where we are at with picture, see [picture.responsiveimages.org](http://picture.responsiveimages.org).

**Comment by yoavweiss** [comment]
I've implemented `src` in the prototype based on the `<video>` model: When `src` is present, `<source>` is ignored.

**Comment by Wilto** [comment]
We’re okay to close this, yeah?

**Comment by yoavweiss** [comment]
I don't think we've added the behavior to the spec. @marcoscaceres ?

**Comment by marcoscaceres** [comment]
Not yet. All src/srcset discussions are blocked waiting on hober letting us know if we are going to merge or not.

**Comment by yoavweiss** [comment]
@marcoscaceres Any news from hober?

**Comment by marcoscaceres** [comment]
Yes. He said to "monkey patch it" on IRC. Basically, what we need to do is just say "where srcset says HTMLImgElement, treat as HTMLSourceElement" or some such.

**Comment by nwtn** [comment]
Given #42's mention that `srcset` overrules `src` and `<source>`, and `src` overrules `<source>`, are we ok to close this?

**Comment by marcoscaceres** [comment]
Yep.
