### ISSUE TITLE
WIP flag is horrible.

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#21]
@hellogeri and I are gonna redo it, as a gift from the RICG to the W3C.

See: http://www.w3.org/TR/2013/WD-html-picture-element-20130219/

**Comment by hellogeri** [comment]
I'm on it!

**Comment by hellogeri** [comment]
Sorry this took forever! Just a couple of mockups; a blue and a grey:

![W3C-Menu-blue](https://f.cloud.github.com/assets/2582293/237645/a82f8f84-881b-11e2-999d-3da8b72fb692.png)
![W3C-Menu-grey](https://f.cloud.github.com/assets/2582293/237646/ad8c4846-881b-11e2-8eab-3ac13896fcf7.png)

**Comment by marcoscaceres** [comment]
Looking great :) Thanks @hellogeri!

**Comment by anselmh** [comment]
Like the blue one more as it follows the design priciples of W3C. Loos good!
Just oen thing: I would remove the box on the closing 'X'…

**Comment by hellogeri** [comment]
@anselmh Good point—I meant to change that but forgot. Will update!

**Comment by darobin** [comment]
BTW these look great — I have an open bug to add them (well, the blue one) to the HTML spec. I'll let you know when I ship it.

Thanks a lot!

**Comment by yoavweiss** [comment]
@hellogeri - can this issue be closed?

**Comment by hellogeri** [comment]
Closed!

**Comment by marcoscaceres** [comment]
We need the CSS and to actually have this in the spec before closing. Can anyone help with that?

**Comment by marcoscaceres** [comment]
@hellogeri what font was used?

**Comment by anselmh** [comment]
@marcoscaceres What exactly is needed? HTML+CSS for that? I could provide that in the next few days if necessary. Where to commit or just a snippet?

**Comment by marcoscaceres** [comment]
@anselmh I've started working on it... but could use a bit of help to make it look better: http://codepen.io/seraphzz/pen/IBfwp

**Comment by anselmh** [comment]
Updated (please look at the css comments): http://codepen.io/anselmh/pen/GFfIi

**Comment by marcoscaceres** [comment]
thanks @anselmh. I wasn't sure from [your comment above](https://github.com/ResponsiveImagesCG/picture-element/issues/21#issuecomment-14671165) if we wanted the background on the close button, but I'm ok to keep it. It's still not quite right in firefox. Regarding Android, don't really mind as specs are not normally viewed on mobile (though we can ). You are also correct, should be fixed.

Also, leave the HTML as it was (i.e., using a strong element). I know it's not quite right, but it's in a section that is post processed by the w3c pub rules service (i.e., we can't change that markup right now).

**Comment by marcoscaceres** [comment]
Regarding not looking right in firefox, the text in the box is getting squished instead of running along most of the length of the box... so the box end up looking really fat. 

![screen shot 2013-06-04 at 2 58 24 pm](https://f.cloud.github.com/assets/870154/605837/e84e5f3a-cd1e-11e2-96f1-557e1e12fcb9.png)

**Comment by anselmh** [comment]
Ah sorry, didn't know (but should have known) about the given HTML-structure. Will fix that soon.

**Comment by anselmh** [comment]
Well, hope this fixes FF + other 'bugs': http://codepen.io/anselmh/pen/qfrsL

**Comment by marcoscaceres** [comment]
Heh, it got a fatter :) I made some modifications: 
http://codepen.io/seraphzz/pen/IlEhv

**Comment by marcoscaceres** [comment]
I threw in a div to get around all the annoying positioning.

**Comment by anselmh** [comment]
Being on another monitor now I see that the gradient seems not to be right:

![screenshot_04 06 13_18_14](https://f.cloud.github.com/assets/399345/606745/f3dd8b2e-cd31-11e2-8192-6e1229687804.png)

**Comment by marcoscaceres** [comment]
well spotted. Fixing.

**Comment by marcoscaceres** [comment]
Ok... it's not exactly the same, but close enough :)

**Comment by marcoscaceres** [comment]
I added a z-index of 1000 to see if that gets around #40. Code updated here:
http://codepen.io/seraphzz/pen/IdHCs

**Comment by marcoscaceres** [comment]
Published a spec using the new WIP flag. http://www.w3.org/TR/telephony/

**Comment by anselmh** [comment]
Oh, the background is half-transparent? This looks a bit awful :( Can we fix it so it is always opaque?

**Comment by marcoscaceres** [comment]
Sure, we can do that.

**Comment by marcoscaceres** [comment]
but wait! didn't you watch the iOS7 launch?! Transparency gives the user context :tongue:

**Comment by anselmh** [comment]
You know you have to change the colors then, too!

**Comment by Wilto** [comment]
This is done and shipped off, yeah?
