### ISSUE TITLE
Update W3C `srcset` doc

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#214]
http://www.w3.org/html/wg/drafts/srcset/w3c-srcset/ is still out there causing confusion, but the process-wheels for getting it replaced are already a-turnin’. Filing this just so we can keep tabs on things.

+@hober

**Comment by Wilto** [comment]
Ref. 3c4933109722b29064bf6e28df14604af7f8841b

**Comment by Wilto** [comment]
What’s the latest on this? @darobin, @hober?

**Comment by Wilto** [comment]
CfC passed; @hober is gonna ping @sideshowbarker about burning that sucker down.

**Comment by yoavweiss** [comment]
Woot!!!

**Comment by zcorpan** [comment]
Secret sources suggest this is gonna pop on Tuesday.

**Comment by Wilto** [comment]
YES.

**Comment by marcoscaceres** [comment]
`<gif image>`

**Comment by Wilto** [comment]
![](http://i.imgur.com/PpmPRu1.gif)
