### ISSUE TITLE
Avoid adding empty `src` to source set

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#217]
As pointed out by @zcorpan on IRC, we add empty src attributes to the source set in http://www.whatwg.org/specs/web-apps/current-work/multipage/edits.html#update-the-source-set
We should probably add a "and the src attribute value contains non-whitespace codepoints" or something of that sort to the list of conditions in 3.1.3

**Comment by zcorpan** [comment]
https://github.com/ResponsiveImagesCG/picture-element/commit/6afa5399d95657fd313fb4863eb7f2f74eac6711

**Comment by zcorpan** [comment]
`<img src=" ">` is not ignored, only the empty string. ("Please leave your sense of logic at the door, thanks!")

**Comment by yoavweiss** [comment]
Oh, OK... That's surprising
