### ISSUE TITLE
Specify UA behavior when multiple candidates have same descriptors?

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#219]
I think it's currently up to the UA what to do when you have e.g. `srcset="foo 2x, bar 2x"`

**Comment by yoavweiss** [comment]
Why is it important to specify it? Is there some compatibility concern around that?

Current Blink/WebKit impl will pick the first one, since it stable sorts the candidates according to their normalized density

**Comment by zcorpan** [comment]
It just seems unnecessary to leave a choice here. (The risk is that another browser will instead pick the last one and then some high-profile site starts relying on that and you have to change to do that instead, or vice versa.)

**Comment by yoavweiss** [comment]
OK. Does the current "pick the first one" approach makes sense? (I wonder
what Gecko does here)

**Comment by tabatkins** [comment]
Makes as much sense as any other option, I think.

**Comment by zcorpan** [comment]
Makes sense to me. We could drop candidates when parsing srcset maybe.

**Comment by zcorpan** [comment]
More important is probably future compat. When we add new descriptors it should be reliable which candidate gets selected by legacy UAs.

**Comment by zcorpan** [comment]
This requirement was present in the old srcset spec. Just need to put it back.
