### ISSUE TITLE
feedback on empty alt used in some examples

### ISSUE THREAD

**Issue by stevefaulkner** [ResponsiveImagesCG/picture-element#220]
a bug was filed on the HTML spec once picture was folded in https://www.w3.org/Bugs/Public/show_bug.cgi?id=26160

The example in question is the first one at http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#introduction-0
advice on how to mark up a similar example can be found here http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#images-that-enhance-the-themes-or-subject-matter-of-the-page-content (the Berjon example)

**Comment by zcorpan** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26232

**Comment by Wilto** [comment]
Found a couple of related things I could patch up on this side of things, but that example is outside the repo. It does read content-image-y to me; I think I’d +1 a quick `alt` value there.

**Comment by zcorpan** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26232 is now fixed. Empty alt is intended.
