### ISSUE TITLE
picture acc mapping

### ISSUE THREAD

**Issue by stevefaulkner** [ResponsiveImagesCG/picture-element#221]
For the purposes of mapping to the acc layer picture has been specified with a implicit semantic of no role [1], which means there is no default role.
This is the same mapping used for other elements that don't expose any UI. It is expected that UAs will simply not expose the element in the accessibility tree. I checked The chrome canary implementation and this is the case. I will check other implementations as they occur.

There was comment about allowing authors to set role=presentation on the picture element, this is not needed as the element will not have a default role that is exposed to users in the first place. 

happy to discuss

[1] http://www.w3.org/html/wg/drafts/html/master/dom.html#sec-strong-native-semantics

**Comment by tabatkins** [comment]
Sounds correct to me. Reopen if you find anything that needs further discussion, I guess.
