### ISSUE TITLE
adding alt text advice to img section when picture used

### ISSUE THREAD

**Issue by stevefaulkner** [ResponsiveImagesCG/picture-element#222]
I am planning to add an example(s) of appropriate alt text for an img inside picture to the HTML spec http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#alt

In most cases i consider it will be follow advice for appropriate alt as if the picture element was not there. but it may be in some cases that through art direction the information contained in the image changes?
any input welcome

HTML bug https://www.w3.org/Bugs/Public/show_bug.cgi?id=26155

**Comment by yoavweiss** [comment]
A few example sites for art-direction (At least used to be...) :
worldwildlife.org
theclymb.com
supercell.net
pocket-lint.com
mindbodyonline.com
lorealparisusa.com
leapmotion.com

**Comment by tabatkins** [comment]
So far, our thought is that the cases where alt needs to change are rare enough that we don't need to deal with it; the vast majority of art-direction doesn't change the nature of the picture sufficiently to justify different text.

**Comment by paciellogroup** [comment]
have added advice and example to spec http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#an-image-in-a-picture-element feedback welcome!

**Comment by marcoscaceres** [comment]
> The picture element has no semantics for users. Use of the picture element does not affect the advice on the text alternative provided for an img. Provide a text alternative for an img element without regard to it being within a picture element. 

I would go with: 

The picture element is just a container for an img element and a set of source elements, so it has no associated semantics (beyond being a container!). It also doesn't itself provide you with any means to include alternative text. As such, always provide a suitable text alternative to the mandatory img element by either using the img's alt attribute or, if it's contained inside a figure element, by using the figcaption element. 

Remember that "art directed" images that rely on picture need to depict the same content (irrespective of size, pixel density, or any other discriminating factor). So the alternative text for an image should always be the same irrespective of which source ends up being chosen by the browser.

**Comment by paciellogroup** [comment]
@marcoscaceres thanks, will wordsmith some.

**Comment by paciellogroup** [comment]
@marcoscaceres have updated used some of your text, thanks!
http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#an-image-in-a-picture-element

**Comment by marcoscaceres** [comment]
Thanks! but sad to see MikeSmith gone :crying_cat_face:

**Comment by Wilto** [comment]
Okay to close?

**Comment by stevefaulkner** [comment]
if people are happy with what I put in the spec, then yes

**Comment by marcoscaceres** [comment]
Seems ok to me.

**Comment by Wilto** [comment]
![](http://bukk.it/thumbsup-bro.gif)
