### ISSUE TITLE
currentSrc and data URIs

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#223]
When setting a srcset attribute with data URI, should the currentSrc value be set in a synchronous manner?
If so, such a technique can be used for future feature detection once we add further descriptors to srcset. On the other hand, such feature detection would require some assumptions regarding the srcset selection algo (which we tell devs they shouldn't be making any).

**Comment by marcoscaceres** [comment]
If currentSrc just reflects the chosen src (irrespective of URL scheme), then it should be fine to do it sync IMO.

**Comment by zcorpan** [comment]
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3066 - seems data: URL images load sync in blink/gecko at least. Will need to fix "update the image data" to do that. (I guess blob: should still be async?)

**Comment by zcorpan** [comment]
It's not sync in Gecko anymore. I don't know when/why this changed.

It's not sync in Safari 8 (on Mac OS X 10.10.1).

It is still sync in Blink.

It's not sync in IE11.

Seems like the trend is towards async loading of `<img src=data:...>`. This happens to be what the spec requires already.

Another reason to avoid sync loading is that it would be blocking while decoding the image which can take some time for very big images.

**Comment by progers** [comment]
Does a spec require synchronous loads? The html5 spec seems to imply synchronous loads are cool:
"A user agent that obtains images immediately must synchronously update the image data of an img element..."

Safari will synchronously load images (datauri or not, so long as they are cached) on refresh:
http://jsfiddle.net/jfe3r3nb/4 (refresh twice)

For this reason, sites must have code to support synchronous loads already.

**Comment by yoavweiss** [comment]
> Does a spec require synchronous loads? The html5 spec seems to imply synchronous loads are cool:
> "A user agent that obtains images immediately must synchronously update the image data of an img element..."

[update the image data](https://html.spec.whatwg.org/multipage/embedded-content.html#update-the-image-data) runs synchronously, but inside it, image load is async, unless the image is in cache (see 5.3).
With that said, we could change the spec if we think it's beneficial.

> Safari will synchronously load images (datauri or not, so long as they are cached) on refresh:
> http://jsfiddle.net/jfe3r3nb/4 (refresh twice)

Yeah, if the image is in memory cache, it will be sync loaded (and I believe sites rely on that behavior, so we cannot remove it).

The main problematic scenario here is the Flash Of Wrong Image™, which admittedly, can also happen with cached images (although not with a broken image). Here's a [test case](http://jsfiddle.net/1gnrwLvy/1/) showing that (reported by @afarkas)

**Comment by yoavweiss** [comment]
As a reference, we've [been discussing](https://codereview.chromium.org/1256233002/) turning data URI resource load to async in Blink

**Comment by yoavweiss** [comment]
dataURIs are now loaded async in Blink, which according to https://github.com/ResponsiveImagesCG/picture-element/issues/223#issuecomment-69772765 they are async everywhere. Closing

**Comment by yoavweiss** [comment]
Correction: They may not be async in WebKit (as image loading is still sync there in general), but that would hopefully soon [change](https://bugs.webkit.org/show_bug.cgi?id=134488).
