### ISSUE TITLE
Support `src` on `<source>`

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#224]
Doing a couple of workshops explaining the whole picture thing to devs, I got a bunch of dropped jaws when explaining that `<source src>` will get ignored.
It seems like a decision we might regret once this thing hits the wild.

What were the reasons we didn't support it? Can we add support for that to the source selection algo?

**Comment by tabatkins** [comment]
We didn't support it because it's useless; we only support `<img src>` because it already exists and works well as a back-compat hack.

What possible reason would they have to use `<source src>`?  Saving a few characters if they're using `<source>` solely for `media`/`type`?

**Comment by yoavweiss** [comment]
There is no reason to use `<source src>` outside the fact that it'd be probably a very common mistake people will do. Since they are used to `<img src>` and `<source src>`, I think that most people would just assume that it should work, and won't understand why it doesn't when it silently fails.

**Comment by nwtn** [comment]
It's just anecdotal, but I've heard this concern from other web devs too. I would be in favour of the spec treating `<source src>` the same way it treats `<img src>`, even if that isn't the _recommended_ way of doing things. Otherwise, I think Yoav's right, it will be a common (and confusing) error.

**Comment by yoavweiss** [comment]
If we strongly believe that `<source src>` is not something that should be supported (personally, I'm not convinced that's the case), maybe an easier way to resolve this would be to spit out console warnings for `<source src>`, making this mistake easier to spot.

**Comment by marcoscaceres** [comment]
Hmm... let's see how we go for now. If the overall response is negative, or we see a lot of it in the wild (people don't usually test so they might add it in a "fire and forget" kinda way) then we can bring it back.

**Comment by Wilto** [comment]
No super-strong feelings on this personally, but I have seen some confusion about it. It seems to click for people right away, but there’s definitely some initial surprise. I also try to keep in mind that the people trying this thing out now and in the near future are probably pretty tuned-in to all this stuff—it’s hard to get much of a read, as things stand now.

Maybe we could get a Specifiction thread goin’, gather some feedback? Couldn’t hurt. +@darobin

**Comment by tabatkins** [comment]
Note that I'm not _opposed_ to allowing `src`, I'd just prefer to avoid it if possible. If it does end up becoming a pain point, I'm fine with allowing it.

**Comment by marcoscaceres** [comment]
Is picturefill allowing it right now?

**Comment by Wilto** [comment]
Nosir.

**Comment by marcoscaceres** [comment]
ok, that's good. I means that at least we won't have interop issues with polyfilled code.

**Comment by zcorpan** [comment]
One benefit for not allowing it is differentiating from `<video>`'s `<source>`. It helps understanding that the processing is not the same.

**Comment by RwwL** [comment]
@zcorpan: I'm not sure an average web author needs to understand or care that processing is not the same. A consistent authoring pattern for these scenarios seems like a benefit to me.

**Comment by derekjohnson** [comment]
FWIW I gave a workshop to two devs and a designer at work and they weren't put out by it not being allowed.

If `<source src>` is allowed will it just be for single sources or will a list of sources be allowed in there too? `src="small.jpg, small.jpg 2x"` doesn't make as much sense as `srcset="small.jpg, small.jpg 2x"` to me, I like the implication that more than one thing can go in.

I don't feel the comparison to `<video>` is a fair one. We are talking about a design issue with `<picture>` not a political one.

**Comment by davidcmoulton** [comment]
People who are already using picturefill are unlikely to erroneously use `<source src` as they already know not to. I like the idea of `src` causing a console warning to be logged, to help later adopters of`picture`. If it's decided that the native implementation of `<picture><source src` should log a warning, it might be worth also making picturefill do the same, for consistency.

**Comment by bjankord** [comment]
+1 for no `<source src`
Seems like it opens up too much to consider from an browser implementation viewpoint.

**Comment by yoavweiss** [comment]
That's encouraging :)
In that case, let's leave things as is (while perhaps adding a console warning to implementations).

Closing. Feel free to open if you strongly disagree.

**Comment by sideshowbarker** [comment]
fwiw I could have the validator emit a special error for source@src with a message saying something as specific and helpful to devs/authors as possible; e.g., "The `src` attribute is not supported for `source`-element images. Use the `srcset` attribute instead." Or whatever the most-helpful "Use ... instead" wording would be.

Above is in the context of earlier comments for this issue; e.g.:

> If we strongly believe that <source src> is not something that should be supported (personally, I'm not convinced that's the case), maybe an easier way to resolve this would be to spit out console warnings for <source src>, making this mistake easier to spot.
> 
> People who are already using picturefill are unlikely to erroneously use <source src as they already know not to. I like the idea of src causing a console warning to be logged, to help later adopters ofpicture. If it's decided that the native implementation of <picture><source src should log a warning, it might be worth also making picturefill do the same, for consistency.

**Comment by yoavweiss** [comment]
Sounds good!
