### ISSUE TITLE
Remove the requirement for descriptors to be a valid int/float

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#225]
The requirement for descriptors to be a valid int/float adds implementation complexity, namely the need to implement and run an int/float validator _before_ actually parsing the int/float, for no good reason.

I prefer that we remove that requirement and accept any int/float that doesn't result in a parsing error, with the following exceptions:
- Trailing garbage would result in an error.
- (optionally) a prefix "+" would result in an error, rather than ignored.

**Comment by zcorpan** [comment]
It's not clear to me what black box behavior change you want.

What do you want to happen for srcset="a 2x 2px"? Drop the candidate or drop the 2px descriptor?

**Comment by yoavweiss** [comment]
Drop the 2px descriptor, same as current spec.
On second thought, I'm not sure there's actual black box difference between current spec and the change I want. If that's the case, I'll simply add a check for a "+" prefix to have it result in an error.

**Comment by zcorpan** [comment]
OK. Yeah if your strict float parser only differs from HTML's "valid float" by the leading + then that would be the same. I take it that the spec is fine as is.
