### ISSUE TITLE
Use media query instead of media-condition in sizes

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#226]
Maybe we should revert to using media query in sizes="" instead of media-condition?

picturefill supports media query.
blink support media query.
validator.nu support media query.
gecko supports media-condition.

I think only supporting media-condition makes the syntax harder to explain because people don't know what it is, whereas they do know what a media query is.

Supporting media query also makes it easier to polyfill correctly.

Validators can still whine about media types when they are used (also in media="") (although I think all/screen/print are OK).

**Comment by yoavweiss** [comment]
If Blink supports full mqs, it's a bug.

With that said, I don't have a strong opinion on which one is better

**Comment by zcorpan** [comment]
Oh, sorry, maybe it supports media-condition now? Looks like it. In that case I guess we should keep it as is and not flip-flop...

**Comment by Wilto** [comment]
Yeah, we should stick with media-condition, I think. Likewise: if Picturefill is still supporting full MQ, that’s a bug.

**Comment by yoavweiss** [comment]
Reopening, since I'm having second thoughts...
Looking at https://github.com/ResponsiveImagesCG/picture-element/issues/230#issuecomment-47816726 I see a use case for a `sizes` attribute that looks like `print 1920px, (max-width: 800px) 100vw, 600px` to serve Hi-Res images for printing purposes.
In the past we claimed that print would be served better by using `<picture>`, since it usually involved art-direction, but I'm no longer sure that's the case.

Thoughts?

**Comment by Nephyrin** [comment]
From yoav's example, `print 1920px, (max-width: 800px) 100vw, 600px` is a list of three items separated by commas -- that sounds like it will get quite messy, but if we can avoid heinous edge-cases and reasonable forward-compatibility, it's easy enough, implementation wise.

Alternatively, we could always go deeper: `[ print 1920px, (max-width: 800px) ] 100vw, 600px`

**Comment by yoavweiss** [comment]
I don't think it would change much from the current implementation, just
replace the media condition check for a media query ( or alternatively,
allow media type instead)

**Comment by tabatkins** [comment]
@yoavweiss: No, just use the media features appropriate for what you want.  Yes, print stylesheets exist today, but they shouldn't, and we should support the new media features that allow people to replace them with appropriate combinations of conditions.  Then it's just another media condition, same as any other layout breakpoint, and can be copied into `<picture>`.

That said, I'm not super-opposed to this.  It's just that the media types are mostly deprecated, with the remaining ones in the process of getting replaced.  Spreading them around to more places isn't great.

@Nephyrin: I have no idea what you're suggesting.  Parsing a `<media-query>` vs a `<media-condition>` is trivial.  Are you parsing that example in some weird way?

**Comment by Nephyrin** [comment]
> Are you parsing that example in some weird way?

Yes, totally. I was mis-recalling `<media-query>` as `<media-query-list>` and mentally read yoav's example as `print, (max-width: 800px) 100vw, 600px`, with the first two items being a `<media-query-list>`, which could possibly be incrementally parsable, but a terrible idea. Disregard.

**Comment by yoavweiss** [comment]
@tabatkins - oh, if we have media features to replace print we can definitely use that instead. What would those be? Resolution/color?

**Comment by tabatkins** [comment]
Depends on what you're looking for! "print" is actually a smorgasbord of features, many of which can be targeted by new features in MQ4.  Often it'll probably just be a matter of extra-high resolution (perhaps switching it to a vector image), or the lack of animation (switching it to a chosen still image).  These are covered by the `(resolution)` and `(update-frequency)` features, respectively.

If there are any missing features, we can expand the spec.

**Comment by yoavweiss** [comment]
OK, I'm totally convinced that MQ4 is the place to resolve that use case, if it's not already resolved by `(resolution)`/`(update-frequency)`/`(color)`.
Closing again! :)
