### ISSUE TITLE
Intrinsic sizing, 'w' resources and zooming

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#228]
We need to decide what to do with intrinsic sizing of 'w' resources and zooming. An example filed by @coldcoder can be found at http://jsfiddle.net/feVXu/embedded/result/

Currently intrinsic sizing of such resources is (more or less) equal to the sizes value picked.
The problem starts when sizes is relative to the viewport and the user decides to zoom in.

Then we can either:
- Zoom the image with the layout, possibly causing the layout to break, since the image no longer respects its intrinsic size as relative to the current viewport. (current Blink impl behavior, which sucks IMO). It also has the nasty effect of changing the image dimensions after a reload.
- Recalculate the image's intrinsic size as relative to the current viewport, meaning that the user can't really zoom the image.

I think the latter option is the lesser of 2 evils.

**Comment by nwtn** [comment]
I have a strong preference for the second option.

**Comment by Nephyrin** [comment]
+1 to the second option. The image (or any layout) being 'unzoomable' is a side effect of the zoom-independent `vw` unit -- I would think that `<img sizes="100vw">` should behave like `<img style="width: 100vw;">` in that regard

**Comment by yoavweiss** [comment]
You're right. `<img style="width: 100vw">` makes this a no-brainer.
Let's update the spec accordingly then.

**Comment by tabatkins** [comment]
By "zoom", do you mean layout zoom or visual zoom?  Ctrl-+ or pinch-zoom?

If the former, option 2 should happen automatically; the size of the viewport changes, thus altering things based on the size of the viewport.  I don't think we need to say anything, do we?

If the latter, the viewport size doesn't change, so nothing happens.

**Comment by tabatkins** [comment]
Oh, I'm fine with a note, particularly as there's already been confusion.  There just doesn't need to be anything normative, as the behavior appears to fall out of the already-defined stuff.
