### ISSUE TITLE
Block insecure assets served via `picture`/`srcset` on TLS sites

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#229]
http://lists.w3.org/Archives/Public/public-webappsec/2014Jun/0245.html

Note that this restriction will not apply to `img [src]`.

I’m two ways on this: if this is going to be how all http-via-TLS assets are handled going forward, I agree that `picture`/`srcset` may be an opportunity to get images in-line with that. On the other hand, if  `picture`/`srcset` are going to be one of only a few restricted cases, I’m not confident that the takeaway will be “looks like I have to change up my asset-serving architecture” so much as “`picture` isn’t working,” and we’ll end up with bloated giant-images-for-everyone secure sites serving a bunch of insecure assets anyway.

Admittedly, I don’t know enough about The Plan for TLS to make any call right now. Thought I’d chuck an issue up for discussion.

**Comment by yoavweiss** [comment]
I think that if it'd be accompanied with "RESOURCE BLOCKED BECAUSE OF MIXED CONTENT!!!!!111" console warnings, people will get it and fix their sites.
And AFAIK, the intention is to block all new types of resources in mixed content scenarios.
@mikewest?

**Comment by Wilto** [comment]
> And AFAIK, the intention is to block all new types of resources in mixed content scenarios.

Yeeeah, being the first and (for now) only scenario where resources are blocked wouldn’t really appeal to me. I think it could end up being a barrier to `picture` adoption, if the aim is to push everyone to TLS.

**Comment by yoavweiss** [comment]
The aim is not to push everyone to TLS, but to make sure that if you're on TLS, you stay there.

HTTP based picture would still work as usual. but you won't be able have an HTTPS site with HTTP based picture.

**Comment by mikewest** [comment]
`<picture>` isn't the only scenario where resources are blocked. Tomorrow's Chrome Canary will block all mixed content by default with the exception of images, audio, video, and plugin requests. I'm waiting for usage data for the remaining bits.

I would like to carve off some of that "images" block. Subsetting images into "stuff that people aren't using yet, and whose behavior is safe to specify securely" doesn't leave much. `<picture>` and `<img srcset>` seem like reasonable targets.

**Comment by mikewest** [comment]
Also, what @yoavweiss said. :)

**Comment by Wilto** [comment]
Hm. I mean, if http-served stylesheets and scripts are gonna come crashing down, it’s going to be pretty clear that something is amiss for the author.

**Comment by yoavweiss** [comment]
Yup, mixed content scripts not working is bound to get people's attention

**Comment by Wilto** [comment]
@zcorpan, @tabatkins: any thoughts?

**Comment by tabatkins** [comment]
I'm fine with this, particularly since we're getting more aggressive with blocking in general.

**Comment by yoavweiss** [comment]
Since everyone here are cool with this, closing. Please reopen if necessary

**Comment by zcorpan** [comment]
I guess we need two request contexts for `<img>` "image" and "legacy image" (when the parent is not `<picture>` and there is no srcset attribute), with the former being an active request context and the latter optionally blockable request context.

We should say which context to use.

(Though the HTML spec doesn't yet use the Fetch spec.)

cc @annevk

**Comment by mikewest** [comment]
I think @annevk suggested `imageset` in a separate thread. It's not in Fetch yet, and he's on vacation for a bit. We'll have to ping him in a few weeks. :)

**Comment by annevk** [comment]
Yeah, if that works please file a bug on Fetch to add `imageset` or add it to an existing bug on contexts.
