### ISSUE TITLE
`srcset` making requests on resize/zoom

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#230]
So, `srcset`, we’re strongly assuming that no art direction is going on. For this reason, we can get a little tricky with window resizing vs. making requests: if we start with a large window and resize it down, there’s no reason to request the smaller versions of the same image when it can just be scaled down with CSS—save a couple requests, where there’d be no real benefit.

Resizing from small to large is a little more complicated. See the discussion in http://ircbot.responsiveimages.org/bot/log/respimg/2014-07-02#T80671

The gist is that we can save requests when scaling the viewport up, but at the cost of blurry images. This feels a little broken to me, from an author standpoint, where an image would appear distorted “sometimes” and correct itself when the page is reloaded.

Zoom is another matter—the above behavior seems a lot more expected on zoom (see #228).

**Comment by yoavweiss** [comment]
Note that this is all a non-normative discussion. Browsers are free to do whatever they feel is best for their users here.
But, we're trying to establish some sort of "best practice" that would be the baseline upon on which browsers would be able to innovate.

Personally, I tend to leave re-downloading out at first stage of the Blink implementation, to avoid extra resource downloads, and then introduce them for some cases, once we see they provide actual benefit in real life scenarios.

**Comment by Wilto** [comment]
Right—keep in mind that we may not be able to _enforce_ whatever we settle on here, but we can advise.

**Comment by RwwL** [comment]
I agree that the blurry images when scaling up (then "fixed" on refresh) feels a little broken from an author standpoint, but think this may be one of the cases that's such an edge case for the reader standpoint that it's just better to avoid the extra requests.

The bigger question, to me, is why does a dev using srcset lead to the browser's strong assumption that no art direction is going on? Is that part of the spec/definition that I've not noticed before?

**Comment by yoavweiss** [comment]
> The bigger question, to me, is why does a dev using srcset lead to the browser's strong assumption that no art direction is going on? Is that part of the spec/definition that I've not noticed before?

Art-direction should be done with `<picture>`. With `srcset` you have no guaranties (as an author) that the images downloaded would be the ones matching your assumptions regarding DPR, viewport size, etc. And yes, it is part of the spec :)

**Comment by anselmh** [comment]
Wait, art direction doesn’t mean necessarily another format. It could simply be another zoomed crop of the image with same proportions. But still I’d not re-download another resource. Anyway, is resizing a browser a common use-case (except orientation change)?

**Comment by tabatkins** [comment]
A zoomed crop of the image should definitely be used when it's appropriate; you don't want a tiny wide-field view on a small screen, or a hugely blown-up headshot on a large screen, even if the resolutions work out correctly. The spec requires that to be redownloaded, as proper.  (Particularly since we can't tell whether it has the same proportions or not.)

I'm fine with an advisory note that UAs may wish to prioritize downloading a higher-res version when the screen drastically increases in size, just as a reminder to implementors.

**Comment by soukhinov** [comment]
Images must be reloaded when zoom is happening.

I put mathematical formulas in my site in 2 formats: pixel-perfect PNG for one-to-one display, and SVG for scale larger than 100%. I was furious when I discovered that I cannot just zoom page with my formulas in Google Chrome: all formulas became blurry, and I needed to reload page after zoom.

Even worse, when I printed my page on laser printer, I got the same blurry raster images! That is because browser did not bother to reload images before printing, it just send to print what it had already downloaded.

So, to print crisp images, I must zoom-in, then reload, and only then print, which feels completely broken.

**Comment by Wilto** [comment]
@soukhinov: Sorry, this is an issue you were having with the `picture` element or the `srcset`/`sizes` syntax? I ask because you just sent us a lot of very unspecific feedback about images via Twitter earlier today, and concluded with the fact that you were just complaining about “web imperfection.”

**Comment by yoavweiss** [comment]
> A zoomed crop of the image should definitely be used when it's appropriate; you don't want a tiny wide-field view on a small screen, or a hugely blown-up headshot on a large screen, even if the resolutions work out correctly

Obviously anything art-directy (so `<picture>`/`<source>`) would be downloaded upon MQ change.
The question here is about quality differences inside `srcset`. (so the only negative effect would be blurriness, not distortion or layout breakage)

Anyway, from the feedback so far, seems like the baseline behavior should be to download higher-res resources according to dimensions + DPR (while considering zoom), and then optimize on that.

> I'm fine with an advisory note that UAs may wish to prioritize downloading a higher-res version when the screen drastically increases in size, just as a reminder to implementors.

Yeah, a note outlining the "baseline" behavior is probably a good idea

**Comment by marcoscaceres** [comment]
@soukhinov this is really valuable feedback, btw. Please note that we are trying to make sure that the use cases are met by browsers. For instance, we've known for a long time that printing was going to be an issue that needed to be addressed - and that zooming also needs to be taken into consideration. See: 
- [Matching media features and media types](usecases.responsiveimages.org/#matching-media-features-and-media-types) - the SVG/printing problem is described there. 
- [Relative units](http://usecases.responsiveimages.org/#relative-units) - zooming problem described there.  

It's both bad and good that you are hitting these problems right now - bad in that you are frustrated, good in that we knew about them from early in picture's design. It means we have some more work to do, but it's certainly the purpose of the spec to make sure your use cases are addressed in implementations.

**Comment by soukhinov** [comment]
It is about `srcset`. It seems that my Google Chrome version still does not support picture, so I was not able to experiment.

P.S. Sorry for Twitter messages. I have just deleted them.

**Comment by yoavweiss** [comment]
@soukhinov - Thanks for the feedback. You can always also open a bug at crbug.com and cc me on it for any issues with the srcset/sizes/picture implementation in Blink (Chrome/Opera).

**Comment by soukhinov** [comment]
That is my code (that I was talking about), which produces blurry image on printer, because browser does not reload image when printing:

`<img src="formula.png" srcset="formula.png 1x, formula.svg 1.01x"/>`

What is wrong with it?

Related Chrominum bug report I just found: https://code.google.com/p/chromium/issues/detail?id=177836

**Comment by ausi** [comment]
I think downloading larger images if you zoom in or resize the browser is very important. The main reason to zoom in on an image on a mobile phone is to see more details of that image.

To improve performance or rather decrease download size the browser may only re-download images which are visible in the current viewport, or re-download them with higher priority.

Just my two cents.

**Comment by tabatkins** [comment]
> `<img src="formula.png" srcset="formula.png 1x, formula.svg 1.01x"/>`

Note that you can force it to work by using `<picture>` fully:

``` html
<picture>
  <source media="print" srcset="formula.svg">
  <img srcset="formula.png 1x, formula.svg 1.01x">
</picture>
```

**Comment by zcorpan** [comment]
Do you need the png to ever be selected? If not, you can do `<img src="formula.png" srcset="formula.svg 1x">`.

**Comment by yoavweiss** [comment]
@zcorpan & @tabatkins do you think we should add a non-normative text around this? If not, we can close this as far as I'm concerned.

**Comment by tabatkins** [comment]
I don't have a strong opinion, but a non-normative note like what I outlined in https://github.com/ResponsiveImagesCG/picture-element/issues/230#issuecomment-47812774 would probably be useful.

**Comment by JosephSilber** [comment]
@RwwL 

> this may be one of the cases that's such an edge case for the reader standpoint that it's just better to avoid the extra requests

Is rotating your phone into landscape (after loading a page) an edge case?

**Comment by RwwL** [comment]
@JosephSilber Yep, it probably is. Even if it's not an edge case in the sense that it happens more often than I think it really does, is the difference in image clarity on a phone-sized screen in that use case worth the additional request & download? Pretty subjective question, and depends on the image, but to me, most of the time, nope. Same probably goes for any 4:3 tablet. On a 16x9 tablet, maybe it'd be more necessary.

**Comment by JosephSilber** [comment]
@RwwL 

> is the difference in image clarity on a phone-sized screen in that use case worth the additional request & download? [...] most of the time, nope.

Considering a 1920 x 1080 screen resolution (iPhone 6 Plus and many Android phones), that's almost double the pixels in landscape mode. I see a clear difference even on my iPhone 6.

Also, you're assuming that both landscape and portrait have the same layout. You sometimes might actually need a _bigger_ image in portrait mode, if the image only takes up a fraction of the screen's width when in landscape mode (and using the `sizes` attribute).

**Comment by RwwL** [comment]
Sure, but one person's "clear difference" is another person's "bandwidth I didn't need to pay for just for rotating the device."

Now, it's also possible that an overwhelming reason people rotate devices post-load is to get a better look at images, in which case, sure, definitely reload 'em.

**Comment by mdmcginn** [comment]
Since we're only talking about what we suggest browsers should do, browsers should offer user settings such as "Prioritize bandwidth" vs. "Prioritize image quality" - maybe a slider. Then the user could decide. Until AT&T adds a "Bandwidth remaining in monthly data plan" field to my http response headers.

**Comment by zcorpan** [comment]
I've filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=27864 for the printing thing.

As for the rest of this bug, I think the spec should not give advice at all. Browser vendors are capable of figuring it out anyway and any advice in the spec is most likely not going to match any one browser, so it will only serve to confuse people. The spec already gives examples of what the browser can take into consideration, including viewport size and zoom.
