### ISSUE TITLE
Preloading alternate images and switching sources

### ISSUE THREAD

**Issue by Nephyrin** [ResponsiveImagesCG/picture-element#231]

**Comment by Nephyrin** [comment]
Pre-mature enter key usage. Let's try again.

Currently, the spec treats switching sources similarly to switching the source on a basic image, but this might not always be desirable behavior.

Considering a simple `<img srcset="small.jpg 1x, big.jpg 2x">`, the UA may want to switch to the big image (issue 230) when the viewport grows. This would cause the image to vanish and -- visibly, incrementally -- load the higher density version. Ideally, we would want to preload the big image, and then load it from cache only once it is retrieved. This might be doable similar to other UA preloading behavior without breaking spec, but I think UA consistency here would be desirable.

With art direction: Is it better to throw out the existing image and (potentially slowly) download the replacement than to fetch the other image in the background? Authors might want to have a say here -- with art direction that just consists of subtle framing differences, it may be very unwanted behavior to introduce more loading to the page rather than use the less-than-ideal image for the duration. I can see the opposite being true with more significant art-direction changes.

**Comment by yoavweiss** [comment]
And another question @nwtn brought up on IRC - what if the higher-res/larger-viewport image load fails? Do we show a broken image symbol or keep displaying the lower-res/narrow viewport one?

Here again, the answer may differ between res switching and art-direction, and even for art-direction the answer may differ on a case by case basis (so best delegated to authors).

@zcorpan started a thread about all of this a few weeks back, but I can find it now :/

**Comment by tabatkins** [comment]
Ooh, that is something we should cover with normative text, I think.

I believe that if you attempt to load a second source from `srcset` and it fails, you should just ignore the failure, and keep showing the previous source.  If you attempt to load a second source from a new `<source>` and it fails, you should show a broken image icon; again, art-direction needs to be honored precisely, and showing the wrong type of image can be pretty bad.  (Showing a broken image is bad too, but oh well.)

**Comment by Wilto** [comment]
Makes sense to me. Falls right in with the “do whatever” part of `srcset`, and as much as I hate the idea of a busted image showing up after an orientationchange while someone is on the subway, we probably don’t want to start introducing any variance to `picture` here.

**Comment by zcorpan** [comment]
This is already in the spec. The algorithm for environment changes says to
do nothing If the load fails. It says to swap when the image is completely
loaded. It might not be exactly what we want, but it's what's currently
required.

On Thursday, July 3, 2014, Mat Marquis notifications@github.com wrote:

> Makes sense to me. Falls right in with the “do whatever” part of srcset,
> and as much as I hate the idea of a busted image showing up after an
> orientationchange while someone is on the subway, we probably don’t want to
> start introducing any variance to picture here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ResponsiveImagesCG/picture-element/issues/231#issuecomment-47917753
> .

## 

Simon Pieters

**Comment by zcorpan** [comment]
Also see https://www.w3.org/Bugs/Public/show_bug.cgi?id=25889

**Comment by Nephyrin** [comment]
Ah, alright, I had not kept up with this part of the spec. I would say the w3 issue covers this entirely
