### ISSUE TITLE
Missing "normalize the source densities" step for sources coming from `<img>`

### ISSUE THREAD

**Issue by tabatkins** [ResponsiveImagesCG/picture-element#233]
Step 3.9 of http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content.html#update-the-source-set normalizes the source densities for `<source>` children, but the sub-algo in step 3.1 doesn't have a similar step.  It needs one inserted between steps 3.1.3 and 3.1.4.

**Comment by zcorpan** [comment]
dup of #227
