### ISSUE TITLE
Percentages not allowed in sizes=""

### ISSUE THREAD

**Issue by gregwhitworth** [ResponsiveImagesCG/picture-element#234]
Was speaking with @yoavweiss and I mentioned how sizes in Chrome Canary doesn't allow you to use percentages and he said that this was because percentages were removed due to author confusion (thinking that the percentages would be relative to its parent). I suggest adding this to the speck, list what units are allowed in the sizes attribute. I also think it might be worth considering doing the same for other units that are relative to the parent and not the root/viewport.

Here is an [example](http://jsfiddle.net/QD4BQ/)

**Comment by tabatkins** [comment]
The spec does explicitly list what types are allowed - it says `<length>`.  Percentages are not `<length>`s (though in some circumstances percentages are resolved relative to a length, of course).

But I'm fine with adding a more explicit note that percentages aren't allowed (and that you probably want to use the vw/vh units).

**Comment by gregwhitworth** [comment]
Thanks!!
