### ISSUE TITLE
Drop candidates with h without w

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#239]
Generally unknown descriptors are just ignored in srcset, they don't cause the candidate to be dropped on the floor. This appears to be the desirable behavior for `type()`, `integrity()` and `h` when `w` is also present. However, it is a bit confusing for `h` when `w` is _not_ present, since it gets interpreted as `1x`.

http://ircbot.responsiveimages.org/bot/log/respimg/2014-08-14#T86602 for discussion.

The fix is a step after 13: "If future-compat-h is not absent and width is absent, let error be yes."

Any opinions?

**Comment by yoavweiss** [comment]
+1, since it'd help us introduce `h` in the future, without causing confusion in legacy UAs
