### ISSUE TITLE
[on hold] Interaction with canvas

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#24]
I think we should codify in the spec how `picture` will interact with `canvas`. If we have something like this:

```
<script>
  var ctx = document.getElementById('canvas').getContext('2d');
  ctx.drawImage(document.getElementById('picture'), 0, 0);
</script>
<canvas id="canvas"></canvas>
<picture id="picture">
  <source id="source1" ... />
  <source id="source2" ... />
</picture>
```

Which `source` gets drawn on the canvas? I assume whichever one is currently shown, but it should probably be spelled out. Also, should we be able to draw from one of the `source` elements directly, rather than via the parent `picture`?

```
  ctx.drawImage(document.getElementById('source1'), 0, 0);
```

This should probably also be spelled out for `srcset`.

**Comment by marcoscaceres** [comment]
Agreed. But this should be done in Canvas Level 2 (i.e., not by us). We should lobby them to add support for it.

**Comment by nwtn** [comment]
http://www.w3.org/html/wg/drafts/2dcontext/html5_canvas/
Anybody know the editors, and have interest in discussing this with them?

**Comment by marcoscaceres** [comment]
We would just need to post to the public-html list, I think. The proposal you put together above is a great start for discussion, I think. It shows the problem quite clearly.

**Comment by marcoscaceres** [comment]
Actually, we could post this bug to their bug tracker component "HTML 2D canvas context":

https://www.w3.org/Bugs/Public/enter_bug.cgi?product=HTML%20WG

**Comment by nwtn** [comment]
on hold pending requests to canvas group

**Comment by tabatkins** [comment]
Since `<picture>` now just drives `<img>`, this is solved automatically.
