### ISSUE TITLE
media attribute with invalid value not parsed correctly

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#242]
[[
If child has a media attribute, and its value is not a valid media query list, or is a valid media query list that evaluates to false, continue to the next child.
]]
http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content.html#update-the-source-set

This should say "If child has a media attribute, and its value does not [match the environment](http://www.whatwg.org/specs/web-apps/current-work/multipage/infrastructure.html#matches-the-environment), continue to the next child."

In particular, `media="all, }"` is not a valid media query list but should still evaluate to true.

**Comment by yoavweiss** [comment]
:+1:
