### ISSUE TITLE
onerror when environment changed?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#249]
As part of a commit to avoid onerror firing when an environment change triggered and image load, @mikewest and myself started [discussing](https://codereview.chromium.org/654253003) whether or not it is the right thing to do. Discussion continued on [IRC](http://echelog.com/logs/browse/blink/1413496800) as well.

@zcorpan - was I correct in my estimate regarding the rational there? Is it to avoid different browsers firing onerror differently?

**Comment by zcorpan** [comment]
The image doesn't change to the broken state, so firing an error event seems slightly off. You can log to the console that the load failed. Is there a use case for notifying JS?

**Comment by yoavweiss** [comment]
/me is back from some quality time with the mother-in-law

@mikewest - are you OK with @zcorpan's explanation? Would you like me to add console errors to https://codereview.chromium.org/654253003/ instead of the unfired onerror?

**Comment by mikewest** [comment]
Yeah, I trust you to make the right decision here. I just want to ensure it's been considered.

**Comment by yoavweiss** [comment]
Cool. Closing then
