### ISSUE TITLE
[on hold] CSS content

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#25]
With CSS3 `content` we can replace the `src` of an `img`:

```
img {
  content: url(image.png);
}
```

This should be possible with `picture` as well, but it's unclear (to me) how it should affect a `source` element. If we replace the content of a displayed `source`, should the page update with the new `content`?

**Comment by nwtn** [comment]
on hold pending request to update [CSS3 Generated and Replaced Content Module](http://www.w3.org/TR/css3-content/)

**Comment by tabatkins** [comment]
`<picture>` now just drives an `<img>`, so this is moot.
