### ISSUE TITLE
SVG format not loading in native picture element when specified in source element with type="image/svg+xml"

### ISSUE THREAD

**Issue by bjankord** [ResponsiveImagesCG/picture-element#251]
I believe I've found an issue with the native picture element and SVG type format. I've created a simple [test case](http://codepen.io/bjankord/full/eGjkv/).

Expected Result:
In browsers that natively support the picture element and SVG format, display the svg image when used in picture element with appropriate type attribute.

Actual Results:
In browsers that natively support the picture element and SVG format, the fallback image displays instead of the SVG image when used in picture element with appropriate type attribute.

Of interest, I [tested the same markup with WebP](http://codepen.io/bjankord/full/gmCzl/) and there were no issues with it loading the WebP format in browsers that natively support the picture element and WebP format.

I havn't filled bugs against Chrome or Opera yet. Was opening I was maybe missing some detail and wanted to share here first.

cc/ @Wilto @yoavweiss @tabatkins @marcoscaceres

**Comment by yoavweiss** [comment]
That's a chrome bug, fixed in canary (and maybe in 39, I don't remember, and on the road).
