### ISSUE TITLE
Require default length in sizes (authoring req)

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#256]
See https://github.com/ResponsiveImagesCG/picture-element/issues/253

since we require the sizes attribute now because defaulting to 100vw is unexpected, do we also want to require a default length for the same resaon?

maybe people will write media-conditions that are mutually exclusive, in which case a default length is not needed ? We could make it a parse error if the algorithm falls back to 100vw.

**Comment by zcorpan** [comment]
I'm leaning towards the simplest option, change the grammar to require the default length.

**Comment by yoavweiss** [comment]
If we're changing the grammar, it'd also change the processing model, not just the authoring requirements, right?

What should the browser do if the default length is not there?

**Comment by zcorpan** [comment]
No need to change the processing model.

**Comment by yoavweiss** [comment]
OK
