### ISSUE TITLE
Image density API

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#259]
Just to track http://ircbot.responsiveimages.org/bot/log/respimg/2015-03-05#T116933 : 
We've discussed adding a way to get/set an image's density from script, and concluded that it'd be awesome if @tabatkins would add it :)

**Comment by zcorpan** [comment]
Dup of https://github.com/ResponsiveImagesCG/picture-element/issues/252 ?

**Comment by yoavweiss** [comment]
Yup. Closing
