### ISSUE TITLE
events and states triggered by picture

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#26]
I haven't seen a discussion of which events should be triggered by `picture` and `source`. There are a lot of possibilities: some of the [media events](http://www.w3.org/TR/html5/embedded-content-0.html#mediaevents) might apply, and presumably the same `load` and `error` events triggered by `img` should apply as well.

Also: will these events only be triggered by `picture`, or by `source` as well?

In addition to the media events, the other media elements also have various `networkState`s and `readyState`s that we might want to consider for `picture`.

**Comment by yoavweiss** [comment]
I completely agree that load/error event should apply (with some indication of which source loaded/errored).
Which media events do you think may apply?

The main difference I see with media elements is that the resource they fetch are _huge_, which download may take many minutes, while the resources `picture` fetches are still images, which download takes a few seconds in the worst case.

**Comment by nwtn** [comment]
I agree that the media events might be more useful with large resources, but I still think it could be handy to have them fire even for smaller resources like an image. Large file size, limited bandwidth, network latency -- all of these can cause images to take longer than expected to load, and some events around that could be helpful.

That said, I'd be in favour of the following events and corresponding states:
- loadstart (precondition: networkState equals NETWORK_LOADING)
- progress (precond: networkState equals NETWORK_LOADING)
- suspend (networkState equals NETWORK_IDLE)
- abort (error is an object with the code MEDIA_ERR_ABORTED, networkState equals either NETWORK_EMPTY or NETWORK_IDLE)
- error (error is an object with the code MEDIA_ERR_NETWORK or higher, networkState equals either NETWORK_EMPTY or NETWORK_IDLE)
- emptied (networkState is NETWORK_EMPTY)
- stalled (networkState is NETWORK_LOADING)
- loadeddata (readyState newly increased to HAVE_CURRENT_DATA or greater for the first time)

loadedmetadata might be useful too. Dimension metadata will obviously be loaded too, but we could also consider the possibility of loading (and giving access to) other metadata.

**Comment by marcoscaceres** [comment]
@nwtn, what other metadata were you thinking of?

**Comment by nwtn** [comment]
I was thinking of EXIF and other standard types of metadata that are often in photos. Things like geolocation data, camera data, timestamps, etc. It would be nice to have APIs for accessing these.

**Comment by marcoscaceres** [comment]
@nwtn agreed, but this is beyond the scope of the spec. This should be a HTML WG issue.

**Comment by nwtn** [comment]
Ya that's fair. So let's not worry about loadmetadata for now. Any thoughts on the others?

**Comment by nwtn** [comment]
closing, covered by #41
