### ISSUE TITLE
Add support for logical operators in media queries passed in sizes strings

### ISSUE THREAD

**Issue by przemyslaw-piatek** [ResponsiveImagesCG/picture-element#266]
As a developer, I'd like to be able to use logical operators in media queries passed in "sizes" strings.
E.g.:

``` html
<img sizes="(min-width: 30em) and (max-width: 50em) 1000px, 500px" srcset="pict1.jpg 500w, pict2.jpg 1000w" alt="Lorem ipsum">
```

This works natively in latest Chrome release.

W3C specs do not and probably will not disallow this:
http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-img-sizes

Plus it complies with current & future MQ specs:
http://drafts.csswg.org/mediaqueries/

**Comment by tabatkins** [comment]
This is already allowed per spec, because we just reference `<media-condition>`, and that's defined in MQ4 to allow boolean algebra.
