### ISSUE TITLE
Writing to `currentSrc`

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#267]
An issue with Picturefill’s support tests (prior to 2.3.1) meant that some browsers with native support for `currentSrc` but no support for `picture` would throw an exception when Picturefill attempted to write to it. This has been addressed in Picturefill, but it’s likely to be a problem for anyone using a version prior to 2.3.1 as new browsers ship without the full respimg suite but _with_ `currentSrc`.

Now, trying to work around this has me thinking: can anyone envision a case where `currentSrc` _should_ be writable?

**Comment by aarongustafson** [comment]
It seems like a naturally read-only property to me.

**Comment by nwtn** [comment]
Doesn't writing to `src` already overrule all the `source`/`srcset` stuff? How would writing to `currentSrc` differ?

**Comment by tabatkins** [comment]
No, there's no reason whatsoever to make it writeable.  It's a convenience property for reflecting the result of a computation in the engine, not an actual attribute of anything.

**Comment by zcorpan** [comment]
> Doesn't writing to `src` already overrule all the `source`/`srcset` stuff?

No, it just sets the `src` attribute. That invokes the "update the image data" algorithm, but that will select the appropriate candidate normally, not ignore everything but `src`.

**Comment by Wilto** [comment]
Yeah, I got nothin’ on this either.
