### ISSUE TITLE
[on-hold]Content-Security-Policy

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#27]
We should define how the [Content-Security-Policy](http://www.w3.org/TR/CSP/) should work for `picture`. Presumably it will use either [`img-src`](http://www.w3.org/TR/CSP/#img-src) or `media-src`, but we should probably just pick one and codify it in the spec.

**Comment by yoavweiss** [comment]
I believe it should be `img-src`. I'll talk to the WebAppSec guys to see if they have strong opinions on the matter.

**Comment by marcoscaceres** [comment]
Having read [the description](http://www.w3.org/TR/CSP/#img-src), img-src sounds right to me.

**Comment by nwtn** [comment]
Agree.

It looks like we'll need to request an update of the language there, though. As it stands, `img-src` is for "the src attribute of an img elements..." (sic); we'll want this to read something like "the src attribute of img or picture elements, or of source elements that are children of picture".

The `media-src` language will also need an update, as right now it applies to "the src attribute of a video, audio, source, or track elements..."; we'll want to specify that it's only `<sources>` elements that are children of `<video>` and `<audio>`;

**Comment by marcoscaceres** [comment]
It's unlikely we will get an update for now at least. We will need to "monkey patch" in our own spec.

**Comment by yoavweiss** [comment]
Looks like CSP will be patched to include a generic language to apply img-src for all image resources (regardless of picture, there are just too many...)
http://lists.w3.org/Archives/Public/public-webappsec/2013Apr/0068.html

**Comment by marcoscaceres** [comment]
win :dancer:

**Comment by nwtn** [comment]
Awesome.

**Comment by yoavweiss** [comment]
Since the CSP guys haven't yet changed the spec language, let's keep this one open and on-hold

**Comment by yoavweiss** [comment]
Trying to kick some dust around this at webappsec, since it wasn't changed since April: http://lists.w3.org/Archives/Public/public-webappsec/2013Aug/0049.html

**Comment by yoavweiss** [comment]
Apparently it's waiting for the fetch spec to define types: http://lists.w3.org/Archives/Public/public-webappsec/2013Aug/0055.html

**Comment by zcorpan** [comment]
I don't think we need to do anything for this bug, now that the fetch for picture is going through the same path as for `<img src>` in the HTML spec, there's no difference from CSP's point of view I think.

**Comment by nwtn** [comment]
Agreed.
