### ISSUE TITLE
IE11 <picture> rendered by JS

### ISSUE THREAD

**Issue by alexcracea** [ResponsiveImagesCG/picture-element#275]
Good day,
Interesting thing that although <picture> is said to not be supported by IE11, it renders fine.
The issue I experenced is only when my picture is not on the page from the beginning but added through JS or any AJAX handlings. The picture is not being visible untill you resize the window in that case.

**Comment by zcorpan** [comment]
Hello! That's nice but this does not seem like an issue with the specification, right?
