### ISSUE TITLE
Imagemaps

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#28]
`img` allows the `usemap` and `ismap` [attributes](http://dev.w3.org/html5/markup/img.html) for imagemaps. We may want to allow these for `picture` too, although it could lead to some interesting problems, especially in cases of art direction.

Thoughts?

**Comment by yoavweiss** [comment]
Since `picture` is mostly about art-direction, I'm not sure I see the use case for supporting image maps.
Anyone has a specific use-case in mind?

**Comment by nwtn** [comment]
I think most of the other use cases we've outlined could be used with image maps, especially resolution switching, matching media features and media types, relative units, and image formats.

**Comment by yoavweiss** [comment]
Correct me if I'm wrong here, but aren't image maps by definition non-
responsive? (Since map values are specified in pixels)
That leaves us with resolution switching &image formats.
Resolution switching on non-responsive image can be resolved with img
srcset.
Image formats is a valid use case, though.

**Comment by nwtn** [comment]
Hmm... I actually hadn't thought of the fact they're defined with pixels. I still think matching media makes sense, as you might want different sources for printing, for b&w devices, etc. But relative units might be out if image maps pixels-only.

**Comment by yoavweiss** [comment]
OK, so media features (B/W, etc) and image formats are the use-cases for this.
I don't think it's extremely important (since usage of image maps is not that frequent nowadays - 0.35% of images in WebDevData), but I'll take a look to see if it can be easily implemented (which is highly possible).

**Comment by nwtn** [comment]
Agree that it's not super common, and possibly (probably) not worth worrying about now in terms of implementation, especially if it's not straightforward. But I do think we should think about it in regards to the spec. IMO, we should try to stick as close to the `img` and media (`audio` and `video`) specs as possible, unless there's good reason not to.

**Comment by nwtn** [comment]
Closing. @yoavweiss feel free to re-open if you think it's necessary.
