### ISSUE TITLE
Querying `src` on `picture`

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#29]
We should define what happens if we do `picture.src` on a `picture` that has no `src` attribute itself, but is displaying one from `source`. I personally think this should return the displayed `src`, but I'm fairly sure this isn't what currently happens with `video` or `audio`.

**Comment by marcoscaceres** [comment]
Agreed - this needs to be specified. But we should follow what video and audio do.

**Comment by nwtn** [comment]
`video` and `audio` use [currentSrc](http://www.w3.org/TR/html51/embedded-content-0.html#dom-media-currentsrc) to get the currently selected `src`. Seems like we should spec the same for `picture`.

**Comment by nwtn** [comment]
closed by PR #42
