### ISSUE TITLE
CORS enabled `picture`

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#30]
Do we need to specify the `crossorigin` attribute, similar to img's? https://developer.mozilla.org/en-US/docs/HTML/CORS_Enabled_Image

This is related to https://github.com/ResponsiveImagesCG/picture-element/issues/24

**Comment by nwtn** [comment]
I think we should.

For implementation, I haven't been able to test this in the Chromium build yet, because I haven't been able to get the layout tests that require Apache to work yet.

**Comment by marcoscaceres** [comment]
Agreed. We definitely will need this if it's going to be usable with canvas. Again, we need to bug the canvas lvl 2 folks to add support for picture.

**Comment by nwtn** [comment]
@yoavweiss is this commit adequate? Can we close this issue?

**Comment by yoavweiss** [comment]
LGTM :)
