### ISSUE TITLE
[on hold] Need to specify DOM constructor

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#31]
We should be able to create a `<picture>` from JS using a DOM NamedConstructor, e.g. `var pic = new Picture` (cf. `var img = new Image` or `var img = new Image()`).

The `img` constructor is:

```
[NamedConstructor=Image(optional unsigned long width, optional unsigned long height)]
```

I don't think we'd need anything different really for `picture`.

**Comment by nwtn** [comment]
I hope I'm misunderstanding this, but from [the embedded content specs](http://www.w3.org/TR/html5/embedded-content-0.html) it looks like `img` has `Image` constructors and `audio` has an `Audio` constructor, but neither `video` nor `source` have constructors.

Futhermore, [source](http://www.w3.org/TR/html5/embedded-content-0.html#the-source-element) says:

> Dynamically modifying a source element and its attribute when the element is already inserted in a video or audio element will have no effect. To change what is playing, just use the src attribute on the media element directly, possibly making use of the canPlayType() method to pick from amongst available resources. Generally, manipulating source elements manually after the document has been parsed is an unnecessarily complicated approach.

Is this not problematic from a responsive POV, if we want to dynamically add in a `source` with a specific media query? We could always do it using `innerHTML` or something I suppose, but it seems like there should be proper constructors for this.

Am I way off base here?

**Comment by marcoscaceres** [comment]
I don't think we need constructors for these right now. Eventually, we want to have an `HTMLPictureElement.addSource()` method, but that's probably a v2 thing.

**Comment by nwtn** [comment]
on hold pending something actually happening with `<picture>`

**Comment by tabatkins** [comment]
I don't think we need a special constructor, do we?  `<picture>` doesn't do anything by itself; a decent factory function would have to generate some `<source>` and `<img>` children as well, which is beyond the scope of this.

**Comment by marcoscaceres** [comment]
don't need it.
