### ISSUE TITLE
[on hold] Need to spec adding picture in contenteditable element

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#32]
An `img` can be added to a `contenteditable` element using `execCommand('insertImage')`. A similar command should be specified for adding a `picture` to a `contenteditable` element.

(Note: although I see `execCommand` referenced [in the HTML5 spec](http://www.w3.org/TR/html5/editing.html#editing-apis), I can't find specific reference to `insertImage`. Is this not actually part of the spec?)

**Comment by nwtn** [comment]
on hold pending request to update [HTML Editing APIs](https://dvcs.w3.org/hg/editing/raw-file/tip/editing.html) spec

**Comment by yoavweiss** [comment]
@nwtn - is this still relevant with the img-driven spec?

**Comment by nwtn** [comment]
Yes? Although I still don't really understand how (or if) the spec does images with `contenteditable`, so it depends on that I think.

@tabatkins is this something you can shed light on?

**Comment by tabatkins** [comment]
No, I don't know anything about contenteditable either. :/

**Comment by zcorpan** [comment]
I think this should be WONTFIX. execCommand doesn't support any new HTML elements. It's thought of as a bad API that browsers need to support for Web compat and it would be good if browsers had interop.

**Comment by yoavweiss** [comment]
Closing because @zcorpan said so :)

**Comment by nwtn** [comment]
@zcorpan @yoavweiss happy to leave this closed and WONTFIX, but do you know if there's a a nice standardy way to do images w/ contenteditable?

**Comment by zcorpan** [comment]
You either use https://dvcs.w3.org/hg/editing/raw-file/tip/editing.html#the-insertimage-command or standard DOM methods.

**Comment by nwtn** [comment]
Ok, so it's still the same `insertImage` command, it's just that it's not necessarily being called via `execCommand`. Is that right? If so, the basics of original issue are still valid: at some point it would be good to discuss an `insertImage`-like command for `picture`.

**Comment by nwtn** [comment]
Assuming I've now understood this properly, this should probably actually stay WONTFIX, but for a different reason: doing `insertImage`-equivalent is too complex for the (probably small) use case. And, since doing it would involve JS anyway, authors who need it can still cook up a custom JS solution.

So: WONTFIX, staying closed.
