### ISSUE TITLE
[on hold] Need to spec accessibility tree and aria roles

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#34]
This came up when testing the webkit/Blink forks, and @yoavweiss suggested it needed to be spec'ed.

See https://github.com/yoavweiss/Blink/issues/5 and https://github.com/yoavweiss/Blink/issues/7

**Comment by anselmh** [comment]
ARIA roles are in the ARIA spec: http://www.w3.org/TR/wai-aria/complete and therefore not specified in the html5 spec.

**Comment by nwtn** [comment]
on hold pending confirmation of/updates to ARIA spec

**Comment by tabatkins** [comment]
`<picture>` now just drives an `<img>`, so this is moot.
