### ISSUE TITLE
"Algorithm for deriving the source image" is unclear

### ISSUE THREAD

**Issue by aarongustafson** [ResponsiveImagesCG/picture-element#35]
In the Note in the unofficial spec (http://picture.responsiveimages.org/#algorithm-for-deriving-the-source-image), the CSS translation seems to indicate that the `source` applied for "all" media would be used first and then the others would be considered, but traditionally media queries are parsed solely in document order, they grant no specificity (as this would seem to imply). As such, the Note does not make sense. 

_Resolution:_ The Note should be updated to reflect the way media queries are handled or it should be explicitly spelled out that the behavior demonstrated is what should happen (e.g. add more media queries to gain greater source weight).

Just as a side note: I still hold that the first-match parsing algorithm used in the `video` element makes the most sense.

**Comment by marcoscaceres** [comment]
Yeah, need to copy what video does. What's there was just us trying to get an idea of how it could work.

**Comment by aarongustafson** [comment]
Do you want me to do that?

**Comment by aarongustafson** [comment]
I just sent a pull request for the tweaks to that section.

**Comment by marcoscaceres** [comment]
Thanks! will review the PR first thing tomorrow. cc @yoavweiss

**Comment by yoavweiss** [comment]
Thanks! Since PR was merged, can we close this issue?
