### ISSUE TITLE
Is picture a media element?

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#37]
We should decide whether `<picture>` should be considered a [media element](http://www.w3.org/TR/html5/embedded-content-0.html#media-elements) as defined in the HTML spec. If it is, this could resolve some of the existing issues (e.g. #26, #33). The problem is that much of the media spec doesn't _really_ apply to images.

If `<picture>` is not a media element and doesn't inherit that specification, we'll need to start grabbing the bits that apply so we can state them explicitly.

**Comment by marcoscaceres** [comment]
Media elements don't apply, unfortunately. But I agree we might need to take certain bits.

**Comment by yoavweiss** [comment]
I agree with @marcoscaceres . `picture` is not a media element, even though some aspects of them may apply.

**Comment by anselmh** [comment]
Picture is clearly not a media element so we have to pic the parts that apply but cannot just copy it.

//edit: sorry wrong btn pressed on mobile :(

**Comment by yoavweiss** [comment]
@nwtn Can we close this issue, and maybe open new issues for specific bits we want to copy from Media elements?

**Comment by anselmh** [comment]
Not being the person asked I am for open up a new one for this to clarify what has to be done.

**Comment by nwtn** [comment]
Sounds good
