### ISSUE TITLE
Issues/notes/examples obstruct WIP notice

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#40]
haven't looked at the css, but it looks like a `z-index` issue.
![Screen Shot 2013-04-24 at 11 21 01 AM](https://f.cloud.github.com/assets/786799/420606/c002fd48-acf2-11e2-8304-bef8ca860049.png)

**Comment by marcoscaceres** [comment]
yeah... we are still waiting for the WIP flag to be recoded

**Comment by marcoscaceres** [comment]
See also: https://github.com/ResponsiveImagesCG/picture-element/issues/21

**Comment by marcoscaceres** [comment]
In #21, I added a z-index of 1000. Need to actually test to see if works.

**Comment by tabatkins** [comment]
No more WIP flag, so I guess we can kill this issue.
