### ISSUE TITLE
[on hold] Borrow interface from Media Elements

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#41]
Following up on #26, #29, #33, and #37.

The interface bits I propose adapting from [Media Elements](http://www.w3.org/TR/html5/embedded-content-0.html#media-elements) are:

```
// error state
readonly attribute MediaError? error;
```

The `MediaError` object itself fits our needs fine, except possibly the name. The four different possible values (`MEDIA_ERR_ABORTED`, `MEDIA_ERR_NETWORK`, `MEDIA_ERR_DECODE`, `MEDIA_ERR_SRC_NOT_SUPPORTED`) are all applicable to `picture`.

```
// network state
         attribute DOMString src;
readonly attribute DOMString currentSrc;
         attribute DOMString crossOrigin;
const unsigned short NETWORK_EMPTY = 0;
const unsigned short NETWORK_IDLE = 1;
const unsigned short NETWORK_LOADING = 2;
const unsigned short NETWORK_NO_SOURCE = 3;
readonly attribute unsigned short networkState;
void load();
DOMString canPlayType(DOMString type);
```

The above are all applicable to `picture`; `buffered` is not and hs been removed. `canPlayType` could be renamed to something like `canShowType`. I also removed `preload`, but perhaps it could be repurposed for something like `defer` (#5)?

```
// ready state
```

Edit per discussion below: Not needed, because `img` already has state, as well as the IDL attribute `complete`. _May_ be needed in the future, if we want to look at meta data.

```
// playback state
// media controller
// controls
// tracks
```

None of these are applicable to `picture`.

Thoughts?

**Comment by anselmh** [comment]
This sounds good to me and is exactly what I would have chosen.

> `canPlayType` could be renamed to something like `canShowType`. 

Yes, `canShowType` is fine.

> I also removed preload, but perhaps it could be repurposed for something like `defer` (#5)?

We all want defer built in. So I think we should define it as you've said. But we cannot adapt the `preload` text here but should use the `defer` text from [`script` elements](http://www.w3.org/html/wg/drafts/html/master/scripting-1.html#attr-script-defer) as preload is completely different and bound to buffering.

> `readyState` could be applicable for picture, but the Media Element state values are not really. I've combined `HAVE_METADATA`, `HAVE_CURRENT_DATA`, `HAVE_FUTURE_DATA`, and `HAVE_ENOUGH_DATA` into `HAVE_DATA`. seeking is not applicable to picture.

`readyState` should be added IMO and helps when using the `defer` attribute or when triggering images via JS.
`HAVE_DATA`: I am not sure if we need this at all. At least we're talking about EXIF data here and I don't know if we need to read that. But it would make spec more flexible if we add `HAVE_DATA` so I am for implementing it but have no strong opinion on it.

**Comment by nwtn** [comment]
> `HAVE_DATA`: I am not sure if we need this at all. At least we're talking about EXIF data here and I don't know if we need to read that. But it would make spec more flexible if we add `HAVE_DATA` so I am for implementing it but have no strong opinion on it.

I was thinking of `HAVE_DATA` as relating to the actual image data, not the meta data; basically that the image was available to be displayed, sort of like `HAVE_ENOUGH_DATA` for the Media Elements. If we want to leave it flexible for metadata, I'd suggest having:

```
const unsigned short HAVE_NOTHING = 0;
const unsigned short HAVE_METADATA = 1;
const unsigned short HAVE_DATA = 2;
```

**Comment by yoavweiss** [comment]
I'd avoid adding APIs to picture that are also relevant to IMG, unless
there's a significant use case for extending IMG as well (or that adding
these APIs to IMG is impossible).
So I'm not sure the havedata stuff is something I'd want to add.

**Comment by anselmh** [comment]
In the case you described (IMG data not meta) I also prefer not adding it...

---

Anselm

**Comment by nwtn** [comment]
In that case, the only possible value for `readyState` would be 0 `HAVE_NOTHING`, which isn't useful. Does that mean you're not in favour of using `readyState` at all?

**Comment by anselmh** [comment]
Regarding / looking at the IMG spec there we have (and we currently have this also in picture spec) the IMG states which give the completely_available state. I am in favor using them.

**Comment by nwtn** [comment]
OK, that makes sense. So let's remove `readyState` and just use the state from `img`. If at some point in the future we decide meta data is an important consideration, we can look at `readyState` again.

**Comment by anselmh** [comment]
@nwtn can you update your first post here with this new decision so we can easily keep track on that?

**Comment by nwtn** [comment]
updated

**Comment by yoavweiss** [comment]
Back from the road, so here's a lengthier response RE all the above attributes/methods:
- `load()` - this is interesting and it goes hand in hand with disabling triggering of the load algorithm when one of the `<source src>` is changed by a script. I'm not sure we specifed that.
- `canPlayType` - Applies to all image resource elements (`<img>`, `<input type=image>`, `<video poster>`, so maybe it should be proposed to extend all image resources? I'm uncomfortable in adding it _only_ to `<picture>`. If anything, `<picture>` needs it less then the rest (with its `type` attr)
- `MediaError` - Again, applicable to all image resources
- `Defer` - We should align to whatever happens with `<img>`. Currently there may be a general resource loading spec forming: https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/ResourcePriorities/Overview.html
- `HAVE_*` attributes - I'd like to state my opposition to it is for 2 reasons: It also applies to `img` and it may be a security threat (I can see scenarios where it exposes 3rd party site login state). I'm also not sure what the use-case for it is.
- `networkState`/`NETWORK_*` - I don't think they apply to `picture`. These may be relevant for a long loading object, but much less relevant for still images.

**Comment by nwtn** [comment]
> canPlayType - Applies to all image resource elements (<img>, <input type=image>, <video poster>, so maybe it should be proposed to extend all image resources? 
> 
> MediaError - Again, applicable to all image resources

I agree that these would be useful in the other image resources, but I don't see that as a compelling reason not to include them in `picture`. I think since, in a lot of ways, `picture` is a monstrous hybrid of `img` and `video`, it creates a useful path to move some of the useful bits from `video` to `img`: spec this stuff in `picture` now and, once they're there, propose adding them to `img`.

> I'm uncomfortable in adding it only to `<picture>`. If anything,`<picture>` needs it less then the rest (with its type attr)

Arguably, then, `video` and `audio` wouldn't need it either, since their sources also support the `type` attribute.

> Defer - We should align to whatever happens with `<img>`.

Agree

> HAVE_\* attributes - I'd like to state my opposition to it is for 2 reasons: It also applies to img and it may be a security threat (I can see scenarios where it exposes 3rd party site login state). I'm also not sure what the use-case for it is.

I'm fine with leaving these out, especially since, as @anselmh pointed out, we can get the same functionality from things that already exist in `img`. The use case right now does not exist (unless and until we want to consider meta data, which it looks like we don't).

That said, I'm not sure I understand the security threat. Could you elaborate?

> networkState/NETWORK_\* - I don't think they apply to picture. These may be relevant for a long loading object, but much less relevant for still images.

In _most_ cases, I think you're right, but I think there are edge cases where this could be useful. Large images, high latency, slow connections, etc. could all create situations where these would come in handy.

**Comment by nwtn** [comment]
In IRC, @marcoscaceres and @yoavweiss both expressed support for splitting `MediaError` and `canPlayType` into a separate proposal, so as not to bloat `picture`. (Guys, please confirm or let me know if I got this wrong.)

@yoavweiss has (above) objected to `networkState`. @marcoscaceres (and others), thoughts on this one?

If we drop all those, the only Media Element overlaps we're left with are `src`, `currentSrc`, `load`, `crossOrigin`, and `load()`. Unless there are objections, I'll start work on a PR to bring these into the `picture` spec.

**Comment by yoavweiss** [comment]
I confirm that I'm in favour of splitting `MediaError` and `canPlayType`
into separate proposals. I also confirm that I object to `networkState`.

Adding `src`, `currentSrc`, `crossOrigin` and `load()` sounds good to me.
Note that `load()` also means that we'd need to redefine the `src`
attribute of `<source>` to avoid kicking off a resource download as soon as
it is modified via a script. I'm not sure what goes on in `<video>` in that
aspect.

**Comment by marcoscaceres** [comment]
I support Yoav's proposal. We should split this into a phase 1, phase 2 thing

**Comment by nwtn** [comment]
on hold pending requests to add `MediaError` and `canPlayType` to `img` etc.

**Comment by yoavweiss** [comment]
This is more or less irrelevant in the latest, img-driven specification. Closing.
