### ISSUE TITLE
Should picture.currentSrc be writeable?

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/picture-element#43]
In the IRC the other day it was suggested that for my [pet usecase](http://ericportis.com/posts/2013/scalables/) (non-art-directed images whose markup isn't tied to a particular layout) lazy/defer + Javascript logic would be the preferred solution. I've been wondering how this might be achievable with `<picture>`.

At its most general, I see `<picture>` as a semantically meaningful way to group multiple versions of the same image which happen to have different technical characteristics (format, resolution, cropping, whatevs) that make them more or less suitable for a given user. The markup _could_ be picking-logic agnostic.

But practically, per the current spec, it seems impossible to implement a custom picking logic. For starters, picture.currentSrc is read-only.

I have vague intuitions that making it writeable and doing whatever else might be necessary to afford that kind of flexibility might be uh, non-trivial. But I figured I'd bring it up for discussion.

**Comment by nwtn** [comment]
Interesting idea. `currentSrc` is read-only simply because that's how it is for media elements, and so far we've just basically straight copied it. Not saying that's a good or bad approach, just letting you know how it got where it is.

Even if `currentSrc` isn't writable, `src` on `<picture>` is, and it overrides anything in `<source>` elements. If you wanted to write your own selection algorithm, it should be fairly trivial to do so, and then set `src` on `<picture>` to override the default one.

**Comment by marcoscaceres** [comment]
The problem is currentSrc could dynamically be changing out from under the developer as the environmental conditions change (and media queries are matched), which makes it kinda useless to have as a writable attribute.

**Comment by eeeps** [comment]
Marcos: that makes sense. Newtn: I hadn't realized that putting a `src` attribute directly on the `<picture>` overrides its children. Setting picture.src is just as easy as setting picture.currentSrc (7 chars easier!), and doing so overrides possible future native algorithm picks, too ... so, yeah... great!

To get a little more concrete about how this might work, let's say I had this HTML:

``` html
<picture id="pic">
    <source src="first.jpg" />
    <source src="second.jpg" data-pickme />
    <img src="fallback.jpg" alt="fallback text" />
</picture>
```

...and this JS:

``` javascript
function pickSource(pictureElement) {
    var sources = pictureElement.querySelectorAll('source');
    for( var i = 0, l = sources.length; i < l; i++ ) {
        if ( sources[i].hasAttribute('data-pickme') ) {
            pictureElement.src = sources[i].src;
            break;
        }
    }
}

window.addEventListener( 'load', function() { 
    pickSource( document.getElementById('pic') );
}, false );
```

Per the spec, first.jpg with its implied `media="all"` would match and be preloaded (let's assume the fallback double-loading issue reaches a sensible conclusion and through a `defer` on the `<img>` or whatever other mechanism the fallback.jpg isn't also pre-loaded). On window.load, second.jpg would be 'picked' by the script, loaded, and painted. Right?

A full discussion of what could or should happen here will probably have to wait until the `defer` thing has been hashed out, but... would `defer` on the `<picture>` give me an opportunity to leave off `media` attributes and make my own pick, without incurring any extra loads? `defer` on all of the `<source>`s?

**Comment by marcoscaceres** [comment]
> would defer on the <picture> give me an opportunity to leave off media attributes and make my own pick, without incurring any extra loads

No. Defer really means "lazy load". To achieve what you want, you would need to take off the src attr and do it the old fashion way... something like: 

```
<picture id="pic">
    <source data-src="first.jpg" />
    <source data-src="second.jpg" data-pickme />
</picture>
```

And then do the JS selection... or some such... but I see that as only really useful for pollyfilling or testing (unless I'm missing something).

**Comment by nwtn** [comment]
Depending on when the lazyload happens relative to when JS is executed, you could have a `src` in the HTML, then use JS to remove it before the lazyload happens. _Then_ you could run your custom selection algorithm.

**Comment by eeeps** [comment]
Marcos - I like the semantics of `<picture>` as a way to group different versions of the same image. Just trying to figure out if it will be workable to build custom logic around it, rather than around custom markup & meaningless divs. You're saying: no (:

But nwtn, you're saying something like...

```
<picture src="fallback.jpg" defer>
   [sources and fallback]
</picture>
```

...could potentially work? Maybe:

```
<picture src="">
   [sources and fallback]
</picture>
```

?

**Comment by eeeps** [comment]
Fiddling with the picture-enabled Chromium build, it looks like an empty src on the `<picture>` "works," though `<picture>`-capable browsers with javascript off get nothing. You could of course go the LQIP/lowsrc/scalables route and put a very low res placeholder in to start...

Will think and tinker more if/when lazy-loading is a thing. Closing the issue. Thanks for helping me think this through on a Saturday morning!

**Comment by marcoscaceres** [comment]
Thanks @eeeps for the discussion. It was really helpful. I really liked what you said in one of your comments above:

> I see <picture> as a semantically meaningful way to group multiple versions of the same image which happen to have different technical characteristics (format, resolution, cropping, whatevs) that make them more or less suitable for a given user. 

If it's cool, I want to add that somewhere in the spec.

**Comment by eeeps** [comment]
The spec? Aw man, that is SUPER COOL!

Here's an example I coded up this afternoon, using the "scalables.js" logic:
- markup: https://github.com/eeeps/scalables/blob/master/examples/scalable-pictures.html
- live: https://eeeps.github.io/scalables/examples/scalable-pictures.html

I see this kind of thing as a use, rather than abuse, of `<picture>` ... playing to its strengths ... building a responsive images solution out of common patterns (like the DOM, vs. srcset's microsyntax) not only makes it more familiar to developers, it opens it up to being hacked on by all of the tools built around those pre-existing patterns. "Hackability" isn't really a use case, but flexibility = adaptability to all kinds of use cases, present and future.

**Comment by marcoscaceres** [comment]
@eeeps took you text and changed it to:

> ```
>  The <code>picture</code> element provides a way to group multiple
>   versions of an image based on different characteristics (e.g., format,
>   resolution, cropping, etc.). This allows the user agent to select the
>   optimum image to present to an end-user based on the browser's
>   environmental conditions and constraints.
> ```

I'm all for hackability. It's a core Web platform principle.
