### ISSUE TITLE
Add lowsrc

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/picture-element#49]
This bug about `img lowsrc` caught my eye, and I wondered if we shouldn't spec `lowsrc` as part of `picture`. It seems like it could be a good part of a responsive solution. Specifically, I would not integrate `lowsrc` into the main resource selection algorithms at all, but specify that a browser may display it in a situation that it feels is appropriate, such as when on a slow network connection, or based on a user pref.

Thoughts?

**Comment by nwtn** [comment]
...and yes, I know this isn't exactly how `lowsrc` behaves on `img`, where the `lowsrc` is loaded first and the `src` loaded once it's done.

**Comment by attiks** [comment]
I agree, keep it out of picture

**Comment by nwtn** [comment]
@attiks I'm saying I think maybe we _should_ add it to `picture`, but with different behaviour than it has for `img`: have it be an optional thing for a user agent to display instead of the normally-selected resource.

**Comment by marcoscaceres** [comment]
This use case is already covered by selecting an appropriate source.

**Comment by nwtn** [comment]
By "source", do you mean a `source` element? If that's the case, then in a situation like this (bad network connection, user pref for low res images), I'm not sure I understand how a user agent would determine which source is optimal. File size and width/height can only be determined once the image has been downloaded, at which point it's too late. The user agent could try to make a guess based on the media queries, but that doesn't seem reliable. An explicit indication that _this resource is tiny_ could be helpful.

**Comment by yoavweiss** [comment]
The media queries determine the source element chosen. Srcset provides a
list of possible resources from which the browser can choose the lowest
quality one, if it sees fit. I don't see how a global lowsrc will improve
things, nor what resource (adapted to which layout) would devs place in it

**Comment by nwtn** [comment]
As you said, the discussion before was to allow a UA to choose the lowest quality `srcset` if it sees fit. I think there's advantage to allowing to override the choice of a `source` as well, if it sees fit. Perhaps that doesn't mean a global `lowsrc` on `picture`, but instead `lowsrc` prop on a particular `source`.

```
<picture>
  <source srcset="small.jpg 1x, small@2x.jpg 2x" media="small" />
  <source srcset="big.jpg 1x, big@2x.jpg 2x" media="big" />
</picture>
```

Consider a retina MacBook connected via tethering to a 3G network with a data cap. The author could specify that on a large screen, the image should edge-to-edge in the browser, and thus provides a `source` with a 1920x600 JPEG for 1x devices and a 3840x1200 JPEG for 2x devices. The normal selection algorithm would choose the 3840x1200 JPEG, but in this case the browser would know that the connection was bad and grab the lower-res 1920x600 JPEG instead. Good! However, as a user, I wouldn't even want an image that big. My connection sucks and I'm paying by the byte, so I want to set a user pref to get the smallest images possible. Right now the browser doesn't have the capability to override the MQs that selected this `source`, so even though there are smaller image resources available, I'm stuck downloading the big one. If we had something like:

```
<picture lowsrc="small.jpg">
  <source srcset="small.jpg 1x, small@2x.jpg 2x" media="small" />
  <source srcset="big.jpg 1x, big@2x.jpg 2x" media="big" />
</picture>
```

or

```
<picture>
  <source lowsrc srcset="small.jpg 1x, small@2x.jpg 2x" media="small" />
  <source srcset="big.jpg 1x, big@2x.jpg 2x" media="big" />
</picture>
```

...and let the browser bypass the `source` selection, it could display `small.jpg` and save bandwidth. There might be an art direction issue, but the author would be aware of that when specifying `lowsrc`.

**Comment by marcoscaceres** [comment]
You are changing the semantics of `lowsrc`, which is confusing. I can understand the argument that you are making here, but it feels like it's over engineered. 

:star2: Golden rule: keep it simple.

**Comment by nwtn** [comment]
I am indeed changing the semantics. I'm also not stuck on it being called `lowsrc`, so I don't think that's such a big deal. I do think there's a use case here, so if this solution I over-engineered, I'd be happy to discuss other ways to tackle it. Since we all agree screen size != network capacity, I think we should think about ways to handle these types of situations.

**Comment by yoavweiss** [comment]
I understand your point, but I think this use-case can be integrated into
srcset. For example, a developer can define a 0.5x image which will be used
for that purpose.

**Comment by nwtn** [comment]
alright, i'm fine with that.

**Comment by anselmh** [comment]
Well, we already talked about similar issues a year ago. Network detection is not up to us. With our current syntax we provide several different images sizes defined by media-query. 
This means, a browser could force to download only the smallest. For now no browser does provide a setting like this. I would be excited if browsers would offer a user-setting to force a specific 'data-behavior': If the user selects 'slow' it only downloads the small files instead of retina ones. This is written down under section 'network' here: http://www.w3.org/community/respimg/2012/06/18/florians-compromise/
Therefore I do not think it makes sense to include which seems already decided as issue is closed by now.

**Comment by marcoscaceres** [comment]
Opera mini lets you choose only low source images (but it's from their proxies) ... so there is at least one browser that has some small control over this. It's indicative of what other browsers could do in the future given multiple source elements.

**Comment by nwtn** [comment]
@anselmh I realize it was talked about before, and I'm not suggesting network detection is up to us. The problem I had is that the browser being able to select the smallest resource only applied to `srcset`, not `source`. My suggestion was to use `lowsrc` to get around that, and say that the browser could ignore `media` and pick a different `source` (or use `lowsrc`) based on that kind of user setting. However, I think @yoavweiss's comment solves the problem; if a <1x resource is specified in `srcset`, the browser can display this when networks are bad, or a user pref is selected. I'm satisfied, but if anybody else thinks it needs revisiting they can re-open.
