### ISSUE TITLE
Add support for title on picture tag

### ISSUE THREAD

**Issue by attiks** [ResponsiveImagesCG/picture-element#51]
Reading the specs is isn't very clear if this is supported, is it?

**Comment by marcoscaceres** [comment]
I think title is a global attribute in HTML... but could certainly clarify.

**Comment by marcoscaceres** [comment]
The attributes list for the element links to the global attributes (one of which is title). I would prefer not to duplicate this in prose.  

Is that ok?  

## 

Marcos Caceres

**Comment by baamenabar** [comment]
In the HTML and HTML5 specs for <img> there's also a link to the global attributes, and a list of specific attributes.
http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content-1.html#the-img-element
http://www.w3.org/TR/html5/embedded-content-0.html#the-img-element
It should be fine as it is.
