### ISSUE TITLE
Image should adapt natural dimensions to density

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/picture-element#61]
See https://github.com/igrigorik/http-client-hints/issues/13

**Comment by kornelski** [comment]
Does that still affect `<picture>`? I thought only early proposals with:

```
 <picture><source media="min-device-pixel-ratio:2"></picture>
```

had problem like client-hints, but since then `@srcset` has been added to `<source>`, so:

```
<picture><source srcset="img 2x"></picture>
```

is fine.

**Comment by marcoscaceres** [comment]
IIUC, the problem is that picture on a 1x display will display the image above at it's natural width/height - thus the image will be twice as big as it should be. Should the image be scaled down (width or height / 96)  to display properly for the pixel ratio?

**Comment by kornelski** [comment]
The `@srcset` spec requires image to display properly, i.e. an image that is 100x100 (device) pixels large will display at 50x50 CSS pixels on 2x screens.

When `<picture>` is used with `<source srcset>` I presume it will inherit the correct behavior and will display crisp images, and not large pixelated images like Client-Hints.

http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content-1.html#current-pixel-density

**Comment by marcoscaceres** [comment]
Right now, it doesn't because the algorithms don't hook into that properly. Will clarify that and add some tests.

**Comment by tabatkins** [comment]
The spec dictates this now.
