### ISSUE TITLE
Relationship to srcset

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#68]
The relationship to srcset section now doesn't make much sense since the spec defines a modified src attribute instead (that includes some of srcset's syntax)

**Comment by Wilto** [comment]
It _might_ end up making sense yet—Timothy Hatcher was asking about renaming `src` sort-of-back to `srcset`:

http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/2013-November/041596.html

Not sure how we’re gonna end up proceeding here, is all. I mean, I’m cool with naming that thing `srcset`. Maybe we should stash that section away for now?

@marcoscaceres, @tabatkins?

**Comment by tabatkins** [comment]
I just renamed the attribute to srcset.  Don't care much either way.
