### ISSUE TITLE
`src`/`srcset` mis-matching

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#69]
https://github.com/ResponsiveImagesCG/picture-element/blob/gh-pages/index.html#L657

References `srcset` and the examples use the revamped `src` approach. Not sure which one we’re gonna end up going with in the end; see: #68

**Comment by yoavweiss** [comment]
Already have an outstanding PR on that

**Comment by tabatkins** [comment]
I'm fine with switching over to `srcset` to make Apple happy. No skin off my nose.

**Comment by tabatkins** [comment]
Oh yeah, @yoavweiss 's PR was accepted.  Closing!
