### ISSUE TITLE
Preloading based on MQs & `@viewport`

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#7]
`<source>` resources (or `srcset` ones) can be preloaded based on MQs that are evaluated against the viewport's width. That is currently working in the prototype.
However, as pointed out by @igrigorik, that will soon change when the `@viewport` rule (that was recently introduced into WebKit) will be merged into the prototype.
The `@viewport` rule comes to fix the `<meta viewport>` mess, _but_ with a major difference. It can come in an external CSS, and as such, may not be available at the time the PreloadScanner kicks in. This _may_ result in fetching some resource in the PreloadScanner, only to find out later that _other_ resources should have been preloaded, and download them as well.

One way of solving it is to tell Web developers (as part of "best practices") that `@viewport` rules must always be inlined rather than external. That is likely to cause confusion, but I don't see any other way around it at the moment.

Thoughts?

**Comment by Wilto** [comment]
I’ve kicked this question over to the IE10 team for feedback on this issue, since they’re well acquainted with both `picture` and `@viewport` — they’ll be getting back to me shortly, and I’ll post up the discussion publicly.

**Comment by yoavweiss** [comment]
@Wilto Any news on this issue?

**Comment by Wilto** [comment]
They never got back to me. Best to leave this one open—this is gonna have to get sorted out one way or the other, independent of us. Let’s just keep an eye on the topic.

**Comment by yoavweiss** [comment]
Related: during the meetup Mozilla's David Baron mentioned that viewport based preloading is problematic for sub-resources of iframes, in case that they are fetched before the parent document has layout.

I'm not sure this happens often, but it is an edge case where viewport dimensions based preloading (both picture and srcset) may fail.

**Comment by yoavweiss** [comment]
Maybe we should add a non-normative note regarding cases where the viewport may change under the browser's feet: `@viewport` is one, iframes is another. We can also document authoring best practices there, in order to avoid "confusing" the browser.

While these are mostly implementation issues, it might be worth while to address them in the spec.

Thoughts?

**Comment by igrigorik** [comment]
@yoavweiss :+1: to that.
