### ISSUE TITLE
Treatment of `src`/`srcset` on `<img>`

### ISSUE THREAD

**Issue by tabatkins** [ResponsiveImagesCG/picture-element#72]
Should we ignore `src` and `srcset` on the contained `<img>`, or treat them as fallback data (adding them as final sources to the `list of source sets`)?

**Comment by nwtn** [comment]
i'd be in favour of treating them as fallback

**Comment by Wilto** [comment]
Does `video` display a fallback `img` when there are no `media`-matching sources? I think it just comes up blank, yeah? We might want to follow suit here for the sake of consistency, but I agree that treating `img` as the final source makes more sense.

**Comment by yoavweiss** [comment]
Consistency with `video` is long broken (srcset, dependency on fallback `<img>`, etc).
I think we should add img's src/srcset to the end of `list of source sets`. It can even be a recommended syntax, since it's DRYer, leading to something like:

```
 <picture>
    <source media="(width > 600px)" srcset="bla.jpg 400w, bla_big.jpg 800w, bla_huge.jpg 1200w">
    <img src="cropped_bla.jpg" srcset="cropped_bla_2x.jpg 2x">
 </picture>
```

**Comment by Wilto** [comment]
That’s a good point.

**Comment by marcoscaceres** [comment]
I agree, we should add them.

**Comment by yoavweiss** [comment]
Added in https://github.com/ResponsiveImagesCG/picture-element/issues/79
