### ISSUE TITLE
Enabling `src` on source?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#78]
Should we add the possibility of adding an `src` attribute to the `<source>` element?
It can be useful as a shortcut if only art-direction is needed, or if CH is used to do res switching. (with the RW hint).

Alternatively, we can ignore it, since a single URL with no descriptors is perfectly legal with `srcset`.

**Comment by nwtn** [comment]
I like the idea of having `src`.

I'm making this argument, but I don't actually believe it: I could see not having `src` causing author confusion, since it's a pattern they're used to using with `video`/`source`.

**Comment by Wilto** [comment]
I like the idea of having `src` available (though we should keep no-descriptor `srcset` in play), but if it stands to complicate implementation any I could certainly live without it. Like @nwtn said: it will definitely be expected to work.

**Comment by yoavweiss** [comment]
I'm actually torn on this one. On the one hand, I agree that devs will expect it to be there. On the other hand, why didn't we define `srcset` to be `src`? (Mainly because devs would expect `src` to behave like `src`) 

Having 2 attributes won't complicate implementation much, but will uglify the spec & algorithms. Beyond dev expectations, there's no real need for 2 distinct attributes, so I don't know what's the best approach.

**Comment by uniqname** [comment]
Since a valid src value is also a valid srcset value, one could make the
argument that src is only needed for legacy purposes. Since <picture> is a
new element altogether it doesn't need that kind of legacy support. src is
then redundant no? Plus, it would dive home a little more that <source>
within a <picture> is not the same as <source> within <audio> or <video>.

On Thu, Jan 2, 2014 at 3:24 PM, Yoav Weiss notifications@github.com wrote:

> I'm actually torn on this one. On the one hand, I agree that devs will
> expect it to be there. On the other hand, why didn't we define srcset to
> be src? (Mainly because devs would expect src to behave like src)
> 
> Having 2 attributes won't complicate implementation much, but will uglify
> the spec & algorithms. Beyond dev expectations, there's no real need for 2
> distinct attributes, so I don't know what's the best approach.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ResponsiveImagesCG/picture-element/issues/78#issuecomment-31490283
> .

## 

Cory Brown

**Comment by yoavweiss** [comment]
Since no one seems to have a very strong opinion that `src` must be supported, we're probably better off leaving it out for now. Closing, but feel free to re-open if necessary.
