### ISSUE TITLE
`<img>` fallback should not be prefetched

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/picture-element#8]
Currently <img> fallback is being prefetched in the PreloadScanner. It should be ignored. See [related implementation issue 5](https://github.com/ResponsiveImagesCG/RespImg-WebCore/issues/5) for further discussion.

**Comment by yoavweiss** [comment]
Issue fixed in implementation. 
@marcoscaceres - Do you want to explicitly state that in the specification?
IMO we would need an alternative fallback mechanism in any case, see https://github.com/ResponsiveImagesCG/picture-element/issues/5

**Comment by bjankord** [comment]
Yeah, I think it needs to be explicitly stated in the spec. If browsers downloads the image from the src attribute of the fallback img AND the src from the active source tag, it goes against the whole concept of responsive images, which is to prevent unnecessary downloads.

In my mind, the picture element would treat a nested img element the same as a noscript element treats nested img elements. If picture is natively supported by the browser, it should never download the fallback image src from the nested img element.

However, if a browser does not natively support the picture element, it would download the src from the nested img element inside the picture element.

I think this is clear to most CG members but should be ironed out in spec language.
