### ISSUE TITLE
What happens when the media conditions change?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#81]
AFAICT, the current spec doesn't define what happens when the media conditions change. (e.g. sceen resize, orientation change, etc).

Should we define that the [image source selection](http://picture.responsiveimages.org/#select-image-source) algorithm should be triggered in such a case?

**Comment by nwtn** [comment]
yes

**Comment by Wilto** [comment]
Oh fo’ sho’.

**Comment by yoavweiss** [comment]
@tabatkins - Would it be possible to integrate this as part of issue 1 on http://picture.responsiveimages.org/#select-an-image-source ? Would this require changes to the HTML part, or can it be contained?

**Comment by tabatkins** [comment]
Yes, I couldn't figure out a good way to do it, and was going to bug Hixie about it.  The fix is definitely intended to go in the Issue 1 resolution.

**Comment by zcorpan** [comment]
I think this should be covered by HTML's "The user agent may at any time run the following algorithm to update an img element's image in order to react to changes in the environment.".

**Comment by nwtn** [comment]
@zcorpan +1
maybe add a note indicating that one such type of environmental change _could_ be @media condition changes, for clarity's sake?

**Comment by zcorpan** [comment]
@nwtn If you think the HTML spec needs such a note, please file a bug on HTML. I don't think the picture spec should be clarifying what the HTML spec says.

**Comment by nwtn** [comment]
My mistake. I thought the bit you quoted _was_ in the picture spec, referencing 'Selecting an image source'. I didn't realize it was already in WHATWG's `img` spec (I assume added with `srcset`). I'm not fussed enough to bother filing a bug, I think it's clear enough.

**Comment by zcorpan** [comment]
OK. So we can close this bug, right?

**Comment by yoavweiss** [comment]
Yeah, I think we can close it.
