### ISSUE TITLE
Sizes and height/width?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#82]
As part of the review on the WHATWG list, @igrigorik asked what happens when both `sizes@source` and `width@img` are defined.

AFAICT, this is not currently defined, but it should be.

@igrigorik's proposal that `width@img` & `height@img` will be ignored when `sizes@source` is defined for the selected source makes a lot of sense, since it would enable devs to define "fallback dimensions", while defining art-direction based dimensions for browsers that support it.

Any objections?

**Comment by brucelawson** [comment]
SGTM

**Comment by yoavweiss** [comment]
Talked to @tabatkins on irc about it, and we cannot (or shouldn't) do that.

`height`/`width` define the display size of the image, while the `sizes` and `srcset` attributes define the (expected) intrinsic size of the image.
Intrinsic size should not override the display size when the display size is defined.

So basically, devs shouldn't define `height`/`width` for art directed images, unless the display dimensions are identical for all.
In real-life RWD, the images would be contained, so no reflow is expected anyway, even if `height`/`width` are not defined.
