### ISSUE TITLE
Use HTMLElement interface for picture

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#87]
With the current design, the picture element is dumb and doesn't need a dedicated interface, as far as I can tell. It could be useful for feature-checking, but then it seems more reliable to check for srcset/sizes on source. So I suggest we drop HTMLPictureElement and let picture use HTMLElement instead.

**Comment by marcoscaceres** [comment]
I'm 50/50 on this one... on the one hand, I see the value in simplifying the spec... on the other hand, I have a feeling we will end up enhancing this interface in the future so having `HTMLPictureElement` extending `HTMLElement` from the start might save us some pain later (and make this element easier to polyfill). IIUC, it's very cheap to have this interface declared on the element from the start (from an implementation perspective) even if it does nothing.

**Comment by zcorpan** [comment]
Hmm, I guess that's reasonable. OK with WONTFIX.

**Comment by yoavweiss** [comment]
Closing
