### ISSUE TITLE
"update the list of source sets" algorithm should maybe be owned by the img element

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#89]
http://picture.responsiveimages.org/#update-the-list-of-source-sets is an algorithm of picture, but in the current design it's img that is the "driver" and as such maybe it should also own that algorithm. I think it will be easier to get sane behavior, at least in the face of invalid markup.

Consider for instance the following case:

```
<picture> <img src="foo"> <img src="bar"> </picture>
```

With the current spec, I think both images would render "foo". I think it would be better if the algorithm considered source elements and the img itself, rather than source plus any img element.

**Comment by yoavweiss** [comment]
Makes sense. @tabatkins?
