### ISSUE TITLE
Define when "select an image source" is invoked

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#91]
We need to say when select an image source is invoked. This includes dynamic updates. See the last paragraph of http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/2013-November/041574.html

**Comment by yoavweiss** [comment]
Related: https://github.com/ResponsiveImagesCG/picture-element/issues/81

**Comment by yoavweiss** [comment]
Other aspects of the same issue are when to trigger and when not to trigger a resource download when HTMLImageElement encounters an `src` attribute.
I think we should spec the folowing:
- JS based 'src' setting should trigger an immediate download, before the element is added to the DOM
- Parser based 'src' setting shouldn't trigger an immediate download. The full selection algorithm should be triggered once HTMLImageElement is added to the DOM. 
- innerHTML handling is slightly more complicated - we should probably specify that selection algorithm is triggered once the innerHTML section is added to the parent element, if it wasn't already triggered during parsing of the innerHTML value.

**Comment by zcorpan** [comment]
I think "select an image source" should replace http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content-1.html#processing-the-image-candidates

which is called from http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content-1.html#update-the-image-data (step 5) and "The user agent may at any time run the following algorithm" (step 3).

That means that this algorithm should not deal with 'error' event or loading anything, it should just return a URL and a pixel density (null/undefined if no source is found), and the HTML spec takes care of the rest.

We need to say which DOM changes invoke "update the image data". Search for "A user agent that obtains images immediately must synchronously update the image data" in HTML for what it has currently.
