### ISSUE TITLE
Reverse the order of `sizes`?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#92]
While reviewing the example, I found that the current syntax of `sizes` is somewhat less intuitive than what I remember from src-N.

E.g. `(max-width: 30em) 100%, (max-width: 50em) 50%, calc(33% - 100px)` would be clearer IMO if it would be `100% (max-width: 30em), 50% (max-width: 50em), calc(33% - 100px)` since the lengths are positioned between the media queries that impact them.

Does that make sense?

**Comment by eeeps** [comment]
I see your point, but for the expanded syntax (full MQs separated by commas) I slightly prefer the `(MQ) size` order; it feels like a bunch of "[if] (MQ) [then] size" statements, kinda like how media queries work in CSS... the MQs are the cause/condition & the sizes are the effects/result.

I don't think either way would be "wrong", and could definitely get used to the reverse ... the currently spec'd order just feels more natural to me.

**Comment by igrigorik** [comment]
Half a dozen of one six of the other... but, FWIW, I think `(condition) size` is better, since condition is the one that selects which size will be used.

**Comment by yoavweiss** [comment]
Well, If I'm the only one feeling nostalgic about the old srcN syntax, I'll let that go :)

**Comment by yoavweiss** [comment]
Closing for lack of public interest :)
