### ISSUE TITLE
Don't allow CSS escapes?

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#97]
@annevk points out that the new syntax appears to support CSS escapes e.g. in the url in srcset. I'm not sure that is intentional or desirable and it doesn't match "old" srcset.

**Comment by zcorpan** [comment]
Although the media attribute already appears to support escapes, I'm not comfortable with doing that for srcset and sizes.

Also I think this issue is bigger than whether CSS escapes are supported. The error handling is also different from old srcset. If the value doesn't match the grammar, the whole thing is ignored. I think this makes it hard to extend the attributes in the future while providing fallback, for instance if type() is added then legacy UAs would ignore the whole attribute.

**Comment by odinho** [comment]
Old srcset had it as an explicit design feature that it should be possible to extend in future.

Important catch. Question is, does anyone actually think different? How to best fix it? Take parse algorithm from original srcset?

**Comment by yoavweiss** [comment]
I don't think we need to support CSS escapes in sizes and srcset.

**Comment by zcorpan** [comment]
@Velmont yeah I think we should write out the parsing algorithm similar to original srcset.

**Comment by zcorpan** [comment]
Let's discuss sizes separately...

**Comment by yoavweiss** [comment]
Closed by https://github.com/zcorpan/picture-element/commit/8b9af3263a5f7dde37b56b17e43e55db1fddeeae
